### ISSUE TITLE
How do you strip the day names down to the first letter?

### ISSUE THREAD

**Issue by daneelliotthamilton** [excid3/simple_calendar#100]
I'm trying to have the calendar display the first letters of each day as the header. I tried

```
day_names: "date.day_names.charAt(0)"
```

But its displaying  r   a   n   s   l   a  instead of S M T W T F S

**Comment by excid3** [comment]
If you're using the latest version, then you'll need to pass in different lambda for the thead option.

```ruby
    def default_thead
      ->(dates) {
        content_tag(:thead) do
          content_tag(:tr) do
            capture do
              dates.each do |date|
                concat content_tag(:th, I18n.t(options.fetch(:day_names, "date.abbr_day_names"))[date.wday])
              end
            end
          end
        end
      }
    end
```

Change the `concat` line to this to grab the first character of the weekday name

```ruby
                concat content_tag(:th, I18n.t(options.fetch(:day_names, "date.abbr_day_names"))[date.wday].first)
```

**Comment by daneelliotthamilton** [comment]
So I passed in a different lambda which i placed in a helper:
```
 <%= month_calendar thead: dashboard_header |date| do %>
   <%= date.day %>
 <% end %>
```

and in my helper:
```
def dashboard_header
    ->(dates) {
        content_tag(:thead) do
          content_tag(:tr) do
            capture do
              dates.each do |date|
                concat content_tag(:th, I18n.t(options.fetch(:day_names, "date.abbr_day_names"))[date.wday].first)
              end
            end
          end
        end
      }
  end
```

But I'm getting a NameError: undefined local variable or method `options'

**Comment by excid3** [comment]
Dang. I think a variable scoping issue. I'd recommend trying out the 2.0 branch from Github. I've just about refactored everything and you'll be able to tweak this right in the view template instead of this gnarly thing.

**Comment by daneelliotthamilton** [comment]
With 2.0 how do I set the header in the view?

**Comment by excid3** [comment]
Once you install the template, you can just edit the HTML in the view folder instead of all this Ruby hacks that the current version requires.

**Comment by daneelliotthamilton** [comment]
What option should i set to get the abbreviations to S M T W T F S? I tried setting the day names using the CharAt() method and that did not work got back the same letters as before. Or would the editing be done within the block?

**Comment by excid3** [comment]
The code in my example should do it for you, just replace the section in the view template with this

```
I18n.t(options.fetch(:day_names, "date.abbr_day_names"))[date.wday].first
```

And here's an explanation of what that's doing:

```ruby
name_type = options.fetch(:day_names, "date.abbr_day_names")
# This determines which internationalization array to look up

names = I18n.t(name_type)
# This returns the array of ["Sunday", "Monday", "Tuesday"...]

date.wday
# This returns the index of the weekday, so if it's Monday, this returns 1

day_name = names[date.wday]
# We can look up the item at position 1 in the array to get the string. If we do that, this returns "Monday"

day_name.first
# This returns "M" because "Monday" is a string, which is an array of characters. If we ask for the first character, it returns "M"
```

Sorry for the late reply! I've been out on vacation for the past few days.

**Comment by daneelliotthamilton** [comment]
Hey sorry about the late reply looking at this issue once again. I'm not sure where I would be placing that piece of code. Could you post a full example please?

**Comment by excid3** [comment]
If you're using version 2.0, you can just open up the template it installs and edit the line that has this similar code to this on it. It will be called app/views/simple_calendar/month_calendar.html.erb when you install the templates.

**Comment by daneelliotthamilton** [comment]
has_calendar in the model is no longer required? also calling

````
<%= month_calendar do |date| %>
    <%= date.day %>
 <% end %>
````

seems to raise an Argument Error (1 for 0)
