### ISSUE TITLE
how can I include this gem in rails using Parse.com as backend

### ISSUE THREAD

**Issue by sai43** [excid3/simple_calendar#101]
Hi,
I want to integrate this gem in rails app which is used parse.com as backend. which used this gem https://github.com/adelevie/parse_resource. please suggest me.
https://parse.com/

**Comment by excid3** [comment]
Good news! Nothing special is needed in order to use this gem! You'll want to make sure your resources have the start_time attribute so you can pass those events into the calendar but that's no different than normal.
