### ISSUE TITLE
Issue with block.call in the calendar view partials

### ISSUE THREAD

**Issue by klipie245** [excid3/simple_calendar#105]
Hi there,

So.. I found this issue with the gem where the block.call in the calendar view partials outputs the entire object to the HTML view. You can see the attached image. Think it may have been a typo.

To fix the issue this should be changed
```<%= block.call day, sorted_events.fetch(day, []) %>```
To
```<% block.call day, sorted_events.fetch(day, []) %>```

This should be changed in all three view partials.

![screen shot 2015-09-10 at 6 41 31 pm](https://cloud.githubusercontent.com/assets/2122649/9794545/f6aeaab2-57eb-11e5-8090-53f7e8486b77.png)

**Comment by excid3** [comment]
That was totally my bad! Just fixed it and going to release a new version of the gem with the fix! Thanks so much! :metal:
