### ISSUE TITLE
Different result for ERB and HAML

### ISSUE THREAD

**Issue by vwong** [excid3/simple_calendar#107]
I'm trying out the new 2.0 release with HAML and am noticing a difference in rendering between ERB and HAML.  Is this a bug to be filed here? Or would this be a HAML bug?

```erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
```

![erb](https://cloud.githubusercontent.com/assets/466689/9806398/49a6de9c-5887-11e5-870b-a58388cb2dd8.png)

```haml
= month_calendar do |date|
  = date
```

![haml](https://cloud.githubusercontent.com/assets/466689/9806400/4d83c89a-5887-11e5-8c39-924108e86622.png)

This is a brand new Rails project, all gems are their latest as of today.

**Comment by excid3** [comment]
Interesting! That's definitely not right. Thanks for the heads up on this. I'll try to see if I can figure out what's wrong on this tomorrow (unless you have any suggestions).

**Comment by vwong** [comment]
Just tried slim and it works fine... Maybe a haml bug?

**Comment by echarp** [comment]
It seems to be a known problem, haml is directly rendering to the template, and is not being managed in the block.

Some people have found a solution, using `capture_haml`
```haml
= month_calendar do |date|
  - capture_haml do
    = date
```

See http://ruby-on-rails-eq8.blogspot.co.uk/2014/10/yielding-haml-block-will-return-0-zero.html

**Comment by excid3** [comment]
This is really interesting. The `capture_haml` definitely does the trick. I can include this either in the README or we could patch the template to check if Haml is installed to automatically add it. 

Are you guys aware of any better ways we could call this block that would work seamlessly between the different template languages? Do you think it's easy enough to just add this as a note inside the README for Haml users?

**Comment by rodrigoargumedo** [comment]
I would probably say that patch the templates with `haml` and `erb` rendering opts. Dunno if there is an active issue on the haml/haml repo where it discusses this but that is really annoying after all.

**Comment by vwong** [comment]
Thanks for the `capture_haml` suggestion.  Will keep that in mind if I come across something similar in future.

**Comment by excid3** [comment]
I just updated the templates that come with the gem to handle the `capture_haml` method for you automatically if Haml is installed. This should take care of it for you guys and anyone else running into this issue in the future.

Update to 2.0.2 and let me know if that works!

**Comment by excid3** [comment]
I also made a screencast on this if any of you guys are interested in the fix and why it works: https://www.youtube.com/watch?v=_qBsiurkf50

**Comment by vwong** [comment]
Works! Thanks.

**Comment by vwong** [comment]
Actually, we're not quite there yet...  You need to *additionally* check that you're in a Haml template.  Otherwise, the code would crash if you have Haml installed, thus `defined?(Haml)` is `true`, but you're not actually using Haml here.  Edge case, but valid nonetheless. 

````haml
    <% if defined?(Haml) && is_haml? && block_is_haml?(block) %>
````
http://haml.info/docs/yardoc/Haml/Helpers.html
