### ISSUE TITLE
Date entries bleed over on top

### ISSUE THREAD

**Issue by tbbooher** [excid3/simple_calendar#108]
I'm trying the most trivial example:
```
        <%= month_calendar do |date| %>
          <% = date %>
        <% end %>
```
But getting this as a result:
![screen shot 2015-09-11 at 17 19 59](https://cloud.githubusercontent.com/assets/10830/9827614/8d3596ea-58a9-11e5-9fd9-70cb106c063a.png)

any thoughts appreciated.

**Comment by rodrigoargumedo** [comment]
Did you try getting rid of the extra space in `<% =`?

That's a bug that can be quite disturbing.

@excid3

**Comment by tbbooher** [comment]
thanks, I'm pretty sure this is related to haml, working that now.

**Comment by tbbooher** [comment]
duplicate of #107

**Comment by excid3** [comment]
Definitely a HAML bug. I updated the other thread with some thoughts.
