### ISSUE TITLE
Alternate responsive build using divs instead of tables

### ISSUE THREAD

**Issue by rsmithlal** [excid3/simple_calendar#111]
For our use case, we needed the month calendar to scale with screen width and collapse into a stacked layout on mobile. I replaced the whole table layout with divs, and integrated styles from Calendario [https://github.com/codrops/Calendario] to help with the structure. Check out their `Demo 1` and its associated article on Codrops website. I love how it's laid out, and the collapsed view for small screens is great! I may have used their plugin entirely, except that it's completely generated using JS and we needed our pages to be crawlable and cacheable. I could potentially work on a responsive build at some point.

**Comment by excid3** [comment]
I would love to see that and I really love their calendar as well.

Presumably, one of the ways you could solve this by changing the CSS from `display: table-cell;` to `display: block` for the days on smaller screen sizes. It would save people from having to use a whole new template and HTML structure.

I may take a stab at doing a CSS version of it using the same templates.

**Comment by rsmithlal** [comment]
That's more or less what happens in my version, media queries switch the days to 100% width blocks

**Comment by Davidzhu001** [comment]
pretty template.

**Comment by echarp** [comment]
I'm also using media queries to switch to 100% width blocks.

See http://www.agendadulibre.org and play with your browser's width to see the result...

**Comment by rsmithlal** [comment]
Cool site!!

**Comment by bananatron** [comment]
Another option for folks not having to deal with old browsers is flexbox. Switching `flex-direction` from `row` to `column` in based on a media query makes things incredibly easy. It's indistinguishable from magic, really.

**Comment by medright** [comment]
flexbox/css grid implementation perhaps..

**Comment by erniux** [comment]
Hello, I want to share my solution: what I did:

@media screen and (max-width: 600px) {
       table {
           width:100%;
       }
       thead {
           display: none;
       }
        
       tbody td {
           display: block;
           text-align:center;
           width:100%;
       }
        
       .simple-calendar .day {
        height: 100%;
        width: 100%;
       }
}

Hope be helpful :-)
