### ISSUE TITLE
possibly wrong example (custom calendar) ?

### ISSUE THREAD

**Issue by zsan** [excid3/simple_calendar#113]
README.md (custom class), I saw

```
class SimpleCalendar::BusinessWeekCalendar
  private

    def date_range
      beginning = start_date.beginning_of_week + 1.day
      ending    = start_date.end_of_week - 1.day
      (beginning..ending)
    end
end

```

I think it should be `(beginning..ending).to_a` ?

**Comment by excid3** [comment]
Yeah it probably should. I forgot already why I needed the `to_a` but I'm pretty sure there was a reason for it. 

Do you want to update the readme and send a pull request? :)
