### ISSUE TITLE
showing full dates in calendar

### ISSUE THREAD

**Issue by kakamble13052** [excid3/simple_calendar#114]
It is showing full dates instead of showing just day. Working on Rails 4, help appreciated

**Comment by kakamble13052** [comment]
Sorry, my bad. It was a blunder on my part. Issue resolved

**Comment by AaronGaim** [comment]
How you solved this problem?

**Comment by smaziano** [comment]
Require the css in your assets...

--
Sérgio Maziano

**Comment by AaronGaim** [comment]
Not helped, I still get dates as "2015-11-03"

**Comment by smaziano** [comment]
Can you show me how you are iterating?

--
Sérgio Maziano

**Comment by AaronGaim** [comment]
Just 
<%= month_calendar do |date| %>
  <%= date %>
<% end %>

and i get result as on the picture

![this](https://cloud.githubusercontent.com/assets/9059606/11204339/741c1a9e-8d06-11e5-931d-95c2503ad54d.jpg)

**Comment by smaziano** [comment]
Try date.day

--
Sérgio Maziano

**Comment by AaronGaim** [comment]
Thank you it works :)

**Comment by smaziano** [comment]
You welcome...

--
Sérgio Maziano
