### ISSUE TITLE
Rendering multiple month calendars on the same view (3 different months)

### ISSUE THREAD

**Issue by serodriguez68** [excid3/simple_calendar#115]
Hi!

In previous versions it was possible to pass start_date: as an argument to the month_calendar function.
In this version this stopped working.

Is there a way to render multiple calendars with different start dates on the same view?

Thanks!

**Comment by jsmecham** [comment]
I have the same question. I just started upgrading a project from 1.x to 2.0.3 and I am also displaying multiple calendars on a single page. I was passing `start_date` as an option in 1.x, but this does not appear to work any longer.

**Comment by serodriguez68** [comment]
I already checked the source code in detail and as far as I can see, the `<start_date>` symbol is hard coded and is always taken from the page params (no way of passing it through the arguments).

It is an easy fix but I'm asking to check if I may be missing something

**Comment by excid3** [comment]
I was certain I was going to miss something important in the rewrite like this. Thanks for the heads up. I think we can refactor this relatively easily to include that functionality again.

Give me the weekend to work on it?

**Comment by rodrigoargumedo** [comment]
I would love to see this in action.
Date: Fri, 22 Jan 2016 06:21:41 -0800

**Comment by serodriguez68** [comment]
Wow thank! 
By the way... are you open to pull requests? I will be glad to help.

**Comment by excid3** [comment]
Yeah, absolutely. I would love a pull request if you've got the time to take a stab at it.

**Comment by serodriguez68** [comment]
Great! Sorry for the late answer, I already sent you a pull request.
(I'm still learning about building gems and contributing to repos, so If I did anything wrong I would greatly appreciate your honest feedback).

**Comment by excid3** [comment]
Awesome! Thanks for submitting a PR so fast! :) I'll review it tomorrow sometime. :+1: :+1:

**Comment by excid3** [comment]
Merged and released this! Thanks for the PR @serodriguez68 :100:
