### ISSUE TITLE
Not the correct code

### ISSUE THREAD

**Issue by Saneery** [excid3/simple_calendar#117]
**If you'd like to use another attribute other than start_time, just pass it in as the attribute option**

<%= month_calendar(attribute: :starts_at) do |date| %>
  <%= day %>
<% end %>

**Comment by shakycode** [comment]
This is good. Is this standard behavior to pass the start_at field as an attribute or something you guys patched?

**Comment by Saneery** [comment]
undefined local variable or method `day'

**Comment by Saneery** [comment]
This correct code 
```ruby
<%= month_calendar(attribute: :starts_at) do |date| %>
  <%= date %>
<% end %>
```
