### ISSUE TITLE
Render Multiple Simple_Calendar Months?

### ISSUE THREAD

**Issue by thalesmiguel** [excid3/simple_calendar#121]
Hello.
Is it possible to render multiple months at once?
For printing purposes, I need to show various calendar months on screen.
I'd like to, for exemple, print January, October and December/2016 so that I can print all of then at once.

**Comment by excid3** [comment]
Absolutely. You can pass in the `start_date` option to tell the calendar which month to render. You'd just pass that in for each of the calendars and that should do the trick.

**Comment by thalesmiguel** [comment]
Great!!!
Could you inform me how to do so?

**Comment by excid3** [comment]
Should be as simple as:

```erb
<%= month_calendar start_date: Date.new(2016, 12, 1) do |date| %>
  <%= date %>
<% end %>
```

**Comment by thalesmiguel** [comment]
That's odd...
Mine isn't working:

`<%= month_calendar start_date: Date.new(2017, 1, 1) , events: (@meetings + @holidays) do |date, events| %>`

Do you know what am I doing wrong?

**Comment by excid3** [comment]
What's not working with it?

**Comment by thalesmiguel** [comment]
`start-date` is still been set as today.

**Comment by excid3** [comment]
Awesome! :) That'd do it. I probably should have released a minor version to include that update, but oh well. I'll do that next time.
