### ISSUE TITLE
When pushing to heroku Ajax and Date display settings doesn't work 

### ISSUE THREAD

**Issue by Mikeks81** [excid3/simple_calendar#122]
In development i placed my ajax remote: true in the gem file code and adjusted the date display of the calendar there as well. However, after pushing my app to heroku neither work on heroku. All other ajax calls work there. Just none of my adjustements to simple calendar.

**Comment by excid3** [comment]
You might be missing something on your end. Just deployed the ajax example to Heroku and it works just fine. https://damp-thicket-46973.herokuapp.com

**Comment by Mikeks81** [comment]
Your sure does work.. Am i missing something. I have added the remote: true to the navigation links in the gemfile as pictured below. This works lovely locally but like i mentioned it didn't transfer to Heroku. 
<img width="1280" alt="screen shot 2016-03-09 at 10 39 09 am" src="https://cloud.githubusercontent.com/assets/15204499/13640572/2b397746-e5e3-11e5-81b0-4bae0fb4c4f4.png">

**Comment by excid3** [comment]
You can compare your implementation to my repo. https://github.com/excid3/simple_calendar-ajax-example

You'll need the links, the js.erb template, and the template to re-render. That should be it. You can monitor Chrome's network requests to make sure it's making XHR requests when you click the links.

**Comment by Mikeks81** [comment]
Aye, so i'm pretty new to coding and to rails... and it turns out that i just didn't read the documentation properly... i adjusted the gem file directly instead of generating the simple calendar views as mentioned in  the read me. Once i did that all of my changes stuck. Thanks for the support and i hope one day to contribute to this gem!

**Comment by excid3** [comment]
Ah! That would do it. Glad you got it working! :+1: 

And I'll look forward to your pull request in the future! ;)
