### ISSUE TITLE
undefined method "month_calendar" when in production

### ISSUE THREAD

**Issue by jsmonceaux** [excid3/simple_calendar#125]
Hello. I installed the simple_calendar gem and was able to create a pretty neat calendar while in development mode, but as soon as I switched to production, I kept getting an 'undefined method "month_calendar"' error. What am I doing wrong?

**Comment by excid3** [comment]
Hmm, did you accidentally put the gem in the development group in your Gemfile or something?

**Comment by jsmonceaux** [comment]
Yes. :( thanks. Sorry I didn't have a smarter question. Great app. Still getting the hang of it. If you get a chance, a quick how too for noobs like me would be awesome. I can't quite get it to look like the example pic but I chaulk it up to inexperience and not the app. Thanks again my friend. :) 👍🏻

**Comment by excid3** [comment]
That'd do it. :) 

The example is an old one that I did using Bootstrap 2 and some custom CSS. I don't include styles because everyone wants their calendar to look different, but the readme should have some examples of the CSS classes you can write to make the calendar look pretty.

**Comment by excid3** [comment]
Actually I did include a default stylesheet I guess. :) https://github.com/excid3/simple_calendar#default-stylesheet The section beneath this is the CSS classes to customize as well.

**Comment by jsmonceaux** [comment]
I saw that and it works well. I guess I just more schooling on how to use CSS. (Dad'gum newbies) Thanks!

-Scott
**sent from iPhone

J. Scott Monceaux, PM
•CFO/Logistics Coordinator,
 Crazy M Farms, LLC
•Secretary, Cypress Lodge #89
 F&AM of Benton, LA
•Vice-President, IAFF Local 4015
 Professional Firefighters
 Association of Benton, LA
•Fire Captain/EMT and IT manager, 
 Benton Fire District #4
•jsmonceaux@yahoo.com
•(318)-218-0343
