### ISSUE TITLE
Why is this happening

### ISSUE THREAD

**Issue by Crunchwrap78** [excid3/simple_calendar#127]
<img width="1188" alt="screen shot 2016-03-23 at 10 28 31 am" src="https://cloud.githubusercontent.com/assets/14954458/13988953/a6c27794-f0e4-11e5-91f6-74742690856f.png">

gem file is already installed

**Comment by excid3** [comment]
Have you restarted your Rails server after installing the gem?

**Comment by Crunchwrap78** [comment]
Yes and I'm still getting the error

**Comment by excid3** [comment]
What version are you on?

**Comment by Crunchwrap78** [comment]
2.0.2. It's fine though. I added the css file from your repo, but still displayed a bit odd, so I did some changes to the padding and did the time conversions to make look more like a calender. I'll push it up to the example repo

**Comment by king601** [comment]
@Crunchwrap78 I wasn't able to reproduce this on a fresh app on Rails 4.2.6, were you able to resolve this?

My demo-test app I made to try and reproduce this. https://github.com/king601/eventable

(Also I realize this was posted like a month ago, I was just trying to see if I could reproduce this)

**Comment by Crunchwrap78** [comment]
So my fix was to add the css provided, but that was only an initial fix since it stilled displayed the full date on a day instead of just the day, so I then used strftime to make the conversions to only display the day.
Here's a reference http://apidock.com/ruby/DateTime/strftime

**Comment by Crunchwrap78** [comment]
@king601

**Comment by king601** [comment]
would you mind sharing some to help reproduce the bug? Can you verify the version in your Gemfile.lock and share the code which you're using in the view for the calendar?/or share the repo if it's public? 

I wasn't able to reproduce the screenshotted bug, but if you can offer some code to help reproduce the issue it'd help greatly

**Comment by ashishterp** [comment]
I think this might be related. I am on 2.1.4 with Rails 5 RC1 though. After initial gem install and this code in view:

`  .row
    .col-sm-9
      = month_calendar(attribute: :start_date, events: @items) do |date, meetings|
        = date
        = meetings.each do |meeting|
          div= meeting.title
`

I get this:

![image](https://cloud.githubusercontent.com/assets/558055/15733316/4b31eb66-28b7-11e6-9a59-307d24f49899.png)

Seems similar to what @Crunchwrap78 was describing in what was displaying. Thoughts?

**Comment by excid3** [comment]
@ashishterp Yours is display the items and square brackets because you're using the equals operator on the `meetings.each` line. You want to use the normal hyphen instead because the equals always prints out the return value. The return value of an `each` is the original array.

**Comment by ashishterp** [comment]
@excid3 Duh... Thanks! Still having the date formatting issue though. ie. 2016-06-01 instead of just 1 like in example.

**Comment by king601** [comment]
@ashishterp Looks like that's actually the default for it. My sample app I created does the same. I'd probably just do like you're doing.

**Comment by excid3** [comment]
That's just the default formatting for Date objects. You can define your own formats however you like. 

(Fun fact: the reason for that is that you can sort those dates by year-month-day alphabetically without having to interpret the numbers and convert them. Makes for easy organization compared to a format like month-day-year which will be out of order if you sort them alphabetically.)
