### ISSUE TITLE
Rails 5 error

### ISSUE THREAD

**Issue by rtrv** [excid3/simple_calendar#129]
I'm trying to use Simple Calendar in Rails 5 beta 3 application, so I have an error:
`Generating a URL from non sanitized request parameters is insecure!`
I've just put the following code in a view:
```ruby
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
```

Is there any solution?

Regards.

**Comment by excid3** [comment]
Good catch! Definitely a newly enforced feature of Rails 5 it looks like. Kaminari has had the same issue. Going to get this fixed this evening for ya.

**Comment by excid3** [comment]
@rtrv Fixed!

I basically just took a Kaminari's approach to fixing this which should be pretty solid. The templates now call a method on the calendar to get a safe URL for the next and previous links and that should do the trick.

Let me know if you run into any other issues with this, but it looks like that fixes everything from what I can tell.

**Comment by rtrv** [comment]
@excid3 good news, I'm gonna check it today. Thanks!
