### ISSUE TITLE
multiple attributes

### ISSUE THREAD

**Issue by reicheltd** [excid3/simple_calendar#133]
Hey, thank you for this great gem!

Would it be possible to use multiple attributes like so:

`month_calendar events: (@events + @holidays), attribute: (:start_time, :due_date) do |date, events|`

Because my objects have multiple `datetime` attributes that I would like to render, not only `:start_time`. As you can see I already use something like this for the events.

The rails helper method `alias_attribute :start_time, :due_date` also works, but only for one attribute.

Best Regards,
Daniel

**Comment by excid3** [comment]
You don't need to pass in those extra attributes, only the one you want to sort by initially. It's just the attribute that I use to filter which day the events belong on. If you want to sort internally to those, you can do it inside the blog using a plain Ruby sort.

Then you're free to render anything you want. Due date, start time, name, whatever you like.

```erb
<%= month_calendar events: (@events + @holidays), attribute: (:start_time, :due_date) do |date, events| %>
  <% events.each do |event| %>
    <div><%= event.name %> </div>
    <div>Start Time:<%= event.start_time %></div>
    <div>Due: <%= event.due_date %></div>
  <% end %>
<% end %>
```

**Comment by reicheltd** [comment]
But when `start_time` is `05/01/2016` and `due_date` is `05/30/2016` both get rendered on `05/01/2016`.

I want this single event to be rendered on both dates.

**Comment by excid3** [comment]
Ah okay. In that case, I would just pass in the start time, and then for each day, do a custom filter in a helper for the due_date ones.

```ruby
def due_date_events(events, day)
  grouped = events.sort_by(&:due_date).group_by { |e| e.due_date.to_date }
  grouped[day]
end
```

```erb
<%= month_calendar events: (@events + @holidays), attribute: :start_time do |date, events| %>
  <h4>New Events</h4>
  <% events.each do |event| %>
    <div><%= event.name %> </div>
  <% end %>

  <h4>Due Events</h4>
  <% due_date_events(@events, day).each do |event| %>
    <div><%= event.name %></div>
  <% end %>
<% end %>
```
