### ISSUE TITLE
History Events

### ISSUE THREAD

**Issue by zackexplosion** [excid3/simple_calendar#135]
How can I listing all Events in current months?

Assume I have those Events

``` ruby
Event.create(:start_time => '2014-06-01', :name => '3')
Event.create(:start_time => '2013-06-01', :name => '2')
Event.create(:start_time => '2012-06-01', :name => '1')
```

and the calendar should be

![calendar](https://cloud.githubusercontent.com/assets/5180966/15688943/3613a516-27af-11e6-9f2a-e77bfc8f0016.png)

The only way I thought, is changing all the event's start_time, after I query from the database.

**Comment by AaronGaim** [comment]
For example :
```
<%= month_calendar do |date| %>
    <% events = Event.where("DAY(start_time) = ? AND MONTH(start_time) = ?", date.mday, date.mon) %>
    <% events.each do |event| %>
        <%= event.name %>
    <% end %>
<% end %>

```

**Comment by excid3** [comment]
Whoops, think I lost my reply that I originally typed up. I would either suggest doing the query inside the view like @AaronGaim suggested here or you could query those up front in your controller and then just check the calendar date in the loop to display them.

The other alternative is to do the single query like you mentioned and then just modify dates for objects outside of the current month. That approach at least reduces the database queries and just takes a little modification upfront. So long as you don't save those objects, that'll work just as well.

Whichever one makes more sense to you, go for it!

**Comment by AaronGaim** [comment]
It's just example :) but if you have working example of the proposed method it will be great.

**Comment by zackexplosion** [comment]
OK, This is my complete index action in the controller

``` ruby
  DAYS = (0..31).to_a.join(',')
  # GET /events
  # GET /events.json
  def index

    # current months means current month , prevous month and next month
    current_months = Date.today.month
    current_months = [current_months + 1, current_months, current_months - 1].join(',')

    current_year = Date.today.year

    # this is only for postgres database
    # filter start_time with only day and month
    @events =
      Event.where("extract(day FROM start_time) in (#{DAYS}) AND extract(month FROM start_time) in (#{current_months}) ")

    @events.each do |e|
      # if the star_time's year in not in current year
      # change it to current_year
      if e.start_time.year != current_year
        e.start_time = e.start_time + (current_year - e.start_time.year).year
      end
    end
  end
```
