### ISSUE TITLE
Support for different partial name

### ISSUE THREAD

**Issue by joseramonc** [excid3/simple_calendar#141]
First of all nice gem, I really liked it.

I'd like to choose a different partial (using with different models in different contexts) but still involving `monthly_calendar.rb`.

I think it can be solved by [chaning this method](https://github.com/excid3/simple_calendar/blob/master/lib/simple_calendar/calendar.rb#L58), supporting an option for the partial among other things

I'm able to work in this if you're interested in merging this feature.

Thanks

**Comment by excid3** [comment]
You can create a new class that's a subclass of the MonthCalendar and it will use the name of that class for the partial. I guess that's a little more work than needed just to change the partial. Thoughts?

**Comment by joseramonc** [comment]
Thanks for the response, It works with creating subclasses.

But I thought it would be faster to implement (and less code to read/create) to just set a `partial` option when calling `month_calendar` like:

```
<%= month_calendar events: @events, partial: 'another_month', do |date, events| %>
   ...
<% end %>
```

**Comment by excid3** [comment]
Yeah, I think having to subclass but not change anything is a little too much work for that use case.

Feel free to send a PR over!

**Comment by excid3** [comment]
Thanks dude! :metal: :metal:

**Comment by joseramonc** [comment]
Thank you for your work in this gem, it's appreciated! 🍻
