### ISSUE TITLE
Adding a class based on an event type to the td? 

### ISSUE THREAD

**Issue by sylverfyst** [excid3/simple_calendar#150]
Where would I go about doing something like this? 

I'd like to color the day td based on the event type stored in my event.

**Comment by excid3** [comment]
A couple different ways:

1. You could install the views and simply customize the td class there.
2. You could make a div inside the td with the class you want, and make it 100% width and height to cover the cell.

**Comment by sylverfyst** [comment]
Thanks for the speedy response, ended up going with number 2

**Comment by excid3** [comment]
Awesome! 👍
