### ISSUE TITLE
Array off objects in view or []

### ISSUE THREAD

**Issue by Peddz24** [excid3/simple_calendar#151]
When I generate my view, at the bottom off every day, no difference in month or week calendars, there are [] or a array that is filled with rails objects. This is nice for debugging but I don't want that in a customer area. How do I turn it off? Please help me

**Comment by excid3** [comment]
You probably left in an `=` in your loop. `<% events.each %>` not `<%= events.each %>`

**Comment by Peddz24** [comment]
Thanks that's it! Just stupidness.. I reckon..

**Comment by excid3** [comment]
Been there, done that many times myself. :)
