### ISSUE TITLE
Week update

### ISSUE THREAD

**Issue by wgailey24** [excid3/simple_calendar#152]
When going to the calendar page I have it set at weekly starting on Monday, when switching between next and previous links the week number doesn't change once, when just using one of the two it does.
So if hitting next then previous I would end up with two weeks numbered at 47

![screenshot-1](https://cloud.githubusercontent.com/assets/15274481/20431673/4f51b992-ad69-11e6-8456-d60649339ee8.png)

**Comment by excid3** [comment]
Hey @wgailey24, 

Interesting find. So you are setting `Date.beginning_of_week = :monday` somewhere in a config so it's globally applied?

**Comment by wgailey24** [comment]
Not that I can find and ive been through the whole of the config directory and controller but I'm not the one that implemented that change so its possible.

**Comment by excid3** [comment]
I can't remember what the Rails defaults are if they're Monday (they might be) so it might not be in your codebase. Was trying to think of what might be the cause of it, and thought maybe that if it wasn't globally set, maybe you'd see this discrepancy?

I'm not entirely sure, probably need to build an example and app fiddle with it before I can give you an answer on that.

**Comment by wgailey24** [comment]
I would really appreciate that!

**Comment by excid3** [comment]
Yo @wgailey24 I think I figured it out. There are 2 different strftime codes for week number, one is for beginning of week being Sunday and the other is for Monday.

I just patched this in the `fix-week-number` branch. You mind installing that and trying it out to see if that fixes it for you?

```
gem 'simple_calendar', git: 'https://github.com/excid3/simple_calendar', branch: 'fix-week-number'
```

**Comment by wgailey** [comment]
Thanks Chris,

Yeah I'll try it out about 2pm est tomorrow. Getting the last of the days sun and some decent waves tonight.



Best regards,

wgailey24


http://imgur.com/a/iGne9

**Comment by excid3** [comment]
Super jealous. 🛥🏄🌊

**Comment by wgailey24** [comment]
Hey Chris,
Yes, that branch fixed it completely!
Thanks much!

**Comment by excid3** [comment]
Great! I'll do a version bump and then release this on rubygems.

**Comment by wgailey24** [comment]
perfect!

**Comment by excid3** [comment]
v2.2.1 is out!

**Comment by wgailey24** [comment]
Hey chris,

Sorry to be a bother but just read some user feedback and didn't get a
chance to investigate, does simple calendar have issues with year
transitions like going to week 0 instead of going from week one to week 52,
and when hitting next going to week 53?

Best regards,

Wgailey24

**Comment by excid3** [comment]
Oh you know what I forgot to check year transitions. What are you seeing? Might be a fix needed for that. I remember someone said that one of the two started at 0 instead of 1. 

Technically there are more than 52 weeks in a year, so that might be where the 53 came from. 

>There are exactly 52.2857142857 weeks in the year 2016. This is equivalent to 52 weeks and 2 extra days, since there are 366 total days in 2016. Most years have 365 days, but a leap year has 366 days. That adds up to 52 weeks (where each week is exactly 7 days) PLUS 1 or 2 additional days.

**Comment by wgailey** [comment]
Like I said I won't be able to investigate until tomarrow, but from what I was getting in feedback just before I left, it goes to week 0 and I just thought checking if it goes beyond the end of the year might be a good idea too.
Best,
Will
On Nov 22, 2016 6:59 PM, Chris Oliver <notifications@github.com> wrote:Oh you know what I forgot to check year transitions. What are you seeing? Might be a fix needed for that. I remember someone said that one of the two started at 0 instead of 1.
Technically there are more than 52 weeks in a year, so that might be where the 53 came from.

There are exactly 52.2857142857 weeks in the year 2016. This is equivalent to 52 weeks and 2 extra days, since there are 366 total days in 2016. Most years have 365 days, but a leap year has 366 days. That adds up to 52 weeks (where each week is exactly 7 days) PLUS 1 or 2 additional days.

**Comment by excid3** [comment]
I discovered there's also a `%V` which I overlooked before which is the ISO 8601 standard.

```
ISO 8601 week-based year and week number:
The week 1 of YYYY starts with a Monday and includes YYYY-01-04.
The days in the year before the first week are in the last week of
the previous year.
  %G - The week-based year
  %g - The last 2 digits of the week-based year (00..99)
  %V - Week number of the week-based year (01..53)

Week number:
The week 1 of YYYY starts with a Sunday or Monday (according to %U
or %W).  The days in the year before the first week are in week 0.
  %U - Week number of the year.  The week starts with Sunday.  (00..53)
  %W - Week number of the year.  The week starts with Monday.  (00..53)
```

Still not sure what makes the most sense.

**Comment by wgailey** [comment]
To me what makes the most sense would be grey placeholders, ie if the year starts on a Friday; Monday or Sunday through Thursday would simply be replaced with grey blanks, same for the end of the year if it ends on a Wednesday; Thursday through sat or sun would be grey blanks.
Best,
Will 
On Nov 22, 2016 8:07 PM, Chris Oliver <notifications@github.com> wrote:I discovered there's also a %V which I overlooked before which is the ISO 8601 standard.
ISO 8601 week-based year and week number:
The week 1 of YYYY starts with a Monday and includes YYYY-01-04.
The days in the year before the first week are in the last week of
the previous year.
  %G - The week-based year
  %g - The last 2 digits of the week-based year (00..99)
  %V - Week number of the week-based year (01..53)

Week number:
The week 1 of YYYY starts with a Sunday or Monday (according to %U
or %W).  The days in the year before the first week are in week 0.
  %U - Week number of the year.  The week starts with Sunday.  (00..53)
  %W - Week number of the year.  The week starts with Monday.  (00..53)

Still not sure what makes the most sense.

**Comment by wgailey24** [comment]
One of the things I'm actually including in my calander is the ability to
choose weekly or monthly calander and what day of the week it starts on
using some of the simple calendar options.

Biweekly would be nice too with the first week always being the current.

best,

-Will

**Comment by excid3** [comment]
Yeah, one thing you can do is configure the `number_of_weeks` on the week calendar. 

You'll probably have to customize the title or whatever you want it to look like. I'm trying to figure out what the best default will be for the title for the single week, whether that's %V, %U, or %W. I'm wondering if %V was actually the right default to use for the gem as it seems to start counting at 1 instead of 0.

**Comment by wgailey** [comment]
Yeah,
%V is good, weeks 1-53 is all I use and my dates are configured with regex.
Best,
-Will 
On Nov 22, 2016 8:20 PM, William Gailey <notifications@github.com> wrote:One of the things I'm actually including in my calander is the ability to
choose weekly or monthly calander and what day of the week it starts on
using some of the simple calendar options.

Biweekly would be nice too with the first week always being the current.

best,

-Will

**Comment by wgailey** [comment]
Yeah,
%V is good, weeks 1-53 is all I use and my dates are configured with regex.
Best,
-Will
On Nov 22, 2016 8:20 PM, William Gailey <notifications@github.com> wrote:One of the things I'm actually including in my calander is the ability to
choose weekly or monthly calander and what day of the week it starts on
using some of the simple calendar options.

Biweekly would be nice too with the first week always being the current.

best,

-Will

**Comment by wgailey** [comment]
Yeah,
%V is good, weeks 1-53 is all I use and my dates are configured with regex.
Best,
-Will
On Nov 22, 2016 8:23 PM, Chris Oliver <notifications@github.com> wrote:Yeah, one thing you can do is configure the number_of_weeks on the week calendar.
You'll probably have to customize the title or whatever you want it to look like. I'm trying to figure out what the best default will be for the title for the single week, whether that's %V, %U, or %W. I'm wondering if %V was actually the right default to use for the gem as it seems to start counting at 1 instead of 0.

**Comment by wgailey** [comment]
Hey Chris,
So, for week numbers:
Behavior observed:
for 2016 it goes from 0 to 52 then back to 1 in 2017, hitting previous from there it goes to 0 then 51.
Expected behavior:
For 2016 go from 1 to 53 then back to 1 in 2017, hitting previous from there go to 53.
Best,
Will
On Nov 22, 2016 8:13 PM, William Gailey <wgailey24@yahoo.com> wrote:To me what makes the most sense would be grey placeholders, ie if the year starts on a Friday; Monday or Sunday through Thursday would simply be replaced with grey blanks, same for the end of the year if it ends on a Wednesday; Thursday through sat or sun would be grey blanks.
Best,
Will 
On Nov 22, 2016 8:07 PM, Chris Oliver <notifications@github.com> wrote:I discovered there's also a %V which I overlooked before which is the ISO 8601 standard.
ISO 8601 week-based year and week number:
The week 1 of YYYY starts with a Monday and includes YYYY-01-04.
The days in the year before the first week are in the last week of
the previous year.
  %G - The week-based year
  %g - The last 2 digits of the week-based year (00..99)
  %V - Week number of the week-based year (01..53)

Week number:
The week 1 of YYYY starts with a Sunday or Monday (according to %U
or %W).  The days in the year before the first week are in week 0.
  %U - Week number of the year.  The week starts with Sunday.  (00..53)
  %W - Week number of the year.  The week starts with Monday.  (00..53)

Still not sure what makes the most sense.

**Comment by wgailey** [comment]
PS grey areas seem to be already implemented as expected. Nice, very nice!
On Nov 22, 2016 8:13 PM, William Gailey <wgailey24@yahoo.com> wrote:To me what makes the most sense would be grey placeholders, ie if the year starts on a Friday; Monday or Sunday through Thursday would simply be replaced with grey blanks, same for the end of the year if it ends on a Wednesday; Thursday through sat or sun would be grey blanks.
Best,
Will 
On Nov 22, 2016 8:07 PM, Chris Oliver <notifications@github.com> wrote:I discovered there's also a %V which I overlooked before which is the ISO 8601 standard.
ISO 8601 week-based year and week number:
The week 1 of YYYY starts with a Monday and includes YYYY-01-04.
The days in the year before the first week are in the last week of
the previous year.
  %G - The week-based year
  %g - The last 2 digits of the week-based year (00..99)
  %V - Week number of the week-based year (01..53)

Week number:
The week 1 of YYYY starts with a Sunday or Monday (according to %U
or %W).  The days in the year before the first week are in week 0.
  %U - Week number of the year.  The week starts with Sunday.  (00..53)
  %W - Week number of the year.  The week starts with Monday.  (00..53)

Still not sure what makes the most sense.

**Comment by excid3** [comment]
You wanna try using the master branch? I am still using %U and %W, but I changed it to always use the first day of the week to calculate the week number.

I don't know if this is better or worse than using %V across the board.

**Comment by wgailey24** [comment]
Yeah,

I'll update it to the master branch on Friday, half day today and off
tomarrow.

Best,

Will

**Comment by excid3** [comment]
Take your time, no rush. And enjoy the turkey! :) 🦃 🦃 🦃

**Comment by wgailey24** [comment]
Hey Chris,

I'm on master branch, still does week 0 thing, and now it cuts off months
too i.e.
Week 47: 11/21-11/27
Week 48: 11/28-11/30
Week 49: 12/05-12/11

Best,

Will

**Comment by excid3** [comment]
Are you on the master branch?

I just tested again and I can't reproduce week 0 at the beginning or end of 2015, 2016, or 2017. I'm using Monday as start of week.

Also I don't see what your issue is with cut off months. This is what I get for week 48:

![week 48](https://d3vv6lp55qjaqc.cloudfront.net/items/0x2y3n3b3W2y0E0t1i0z/Screen%20Shot%202016-11-26%20at%205.32.41%20PM.png?X-CloudApp-Visitor-Id=51470&v=adbb9779)

**Comment by wgailey24** [comment]
I was on the branch you patched previously, then got caught up in something
else. I'll look again Monday morning.

**Comment by wgailey** [comment]
Hey Chris,
Just confirmed on the master branch, advance to when the year gets to 1 hit previous and it will go to week 0.
Best,
Will 
On Nov 26, 2016 6:41 PM, William Gailey <notifications@github.com> wrote:I was on the branch you patched previously, then got caught up in something
else. I'll look again Monday morning.

**Comment by excid3** [comment]
First week of 2017 does that for you? I tried it a bunch of times and it wasn't saying Week 0 for me. *grumble*

**Comment by wgailey24** [comment]
I can send you more details on what I'm using for it in a minuite. :)

**Comment by wgailey24** [comment]
In my calendar view I have:

week_calendar (number_of_weeks: 1, attribute: end_time) do |date|
%b
  %u
   = date.strftime ("%m/%d/%Y")

CSS:

.calendar-title {padding-right: 40%; padding-left: 40%}

.calendar-heading {a:link, a:active, a:hover, a:visited { font: bold
24px/45px Helvetica, Sans-Serif; color: deepskyblue}

GEMFILE:
gem 'simple_calendar', :branch => 'master'

Best,

Will

**Comment by excid3** [comment]
Oh hmm, I think you may have to specify the git url for the gem to make sure you're using it from github.

`gem 'simple_calendar', :git => 'https://github.com/excid3/simple_calendar', :branch => 'master'`

You should see it in the bundle logs to show that it's coming from Github.

**Comment by wgailey** [comment]
Hey,
No more week 0 problems but still getting the month cutoff thing.
i.e. starting at week one hit next until at week 6, then hit previous until at week 4, notice how week 5 is an ever changing 3-4 days but never 7 like it should be?
Best,
Will
On Nov 28, 2016 1:37 PM, Chris Oliver <notifications@github.com> wrote:Oh hmm, I think you may have to specify the git url for the gem to make sure you're using it from github.
gem 'simple_calendar', :git => 'https://github.com/excid3/simple_calendar', :branch => 'master'
You should see it in the bundle logs to show that it's coming from Github.

**Comment by wgailey24** [comment]
It seems to be week/month/year when it should be just week/year

Best
Will

**Comment by wgailey** [comment]
Good morning Chris,
Any updates on the week month cuttoffs?
Best,
Will
On Nov 28, 2016 1:51 PM, William Gailey <notifications@github.com> wrote:It seems to be week/month/year when it should be just week/year

Best
Will

**Comment by excid3** [comment]
You sure those aren't being hidden with CSS or something? I can't reproduce the weeks with missing days. Every week displays the full 7 days of dates for me.

**Comment by wgailey** [comment]
I'll submit it as a new ticket so I can add an image.
On Nov 29, 2016 11:06 AM, Chris Oliver <notifications@github.com> wrote:You sure those aren't being hidden with CSS or something? I can't reproduce the weeks with missing days. Every week displays the full 7 days of dates for me.

**Comment by wgailey24** [comment]
Also not so much missing as grayed out

**Comment by wgailey24** [comment]
Did the week 0 fix git pushed up to ruby gems?

**Comment by wgailey** [comment]
Hey Chris before I leave you be forever, is there a css tag applied on next and previous on the calendar but only those elements?Best,Will On Nov 29, 2016 12:57 PM, William Gailey <wgailey24@yahoo.com> wrote:I'll submit it as a new ticket so I can add an image.
On Nov 29, 2016 11:06 AM, Chris Oliver <notifications@github.com> wrote:You sure those aren't being hidden with CSS or something? I can't reproduce the weeks with missing days. Every week displays the full 7 days of dates for me.

**Comment by excid3** [comment]
Hah, no worries. :) 

Yeah you should be able to highlight those links. You could style against `.calendar-heading a` which you can see here: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_week_calendar.html.erb

Or you could just add the views to your app and then add some classes in.

**Comment by wgailey24** [comment]
I was able to style them with calendar-heading>a but calendar-heading also
plied to things I didn't want styled.

Best,
Thanks again,
Will

**Comment by wgailey** [comment]
Hahaha hey Chris,I know I said you'd be rid of me but is there anyway you could do a quick fix to the week number?if number_of_weeks > 1 then .calendar-title is "week_number -"('week_number+number_of_weeks')Best,Will On Dec 5, 2016 1:59 PM, Chris Oliver <notifications@github.com> wrote:Hah, no worries. :)
Yeah you should be able to highlight those links. You could style against .calendar-heading a which you can see here: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_week_calendar.html.erb
Or you could just add the views to your app and then add some classes in.

**Comment by excid3** [comment]
Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by wgailey** [comment]
Shot ;)On Dec 7, 2016 1:10 PM, Chris Oliver <notifications@github.com> wrote:Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by wgailey** [comment]
All working the way it should, let me know when it's accepted and pushed into rubygems so I can stop using my local directory.Best,Will On Dec 7, 2016 3:45 PM, William Gailey <wgailey24@yahoo.com> wrote:Shot ;)On Dec 7, 2016 1:10 PM, Chris Oliver <notifications@github.com> wrote:Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by wgailey** [comment]
Any news on that dynamic week calendar title PR?On Dec 7, 2016 1:10 PM, Chris Oliver <notifications@github.com> wrote:Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by wgailey** [comment]
Hey Chris,Any news on that dynamic week calendar title PR I did?Best,Will On Dec 7, 2016 1:10 PM, Chris Oliver <notifications@github.com> wrote:Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by wgailey** [comment]
Hey Chris,I was just wondering if you reviewed the PR at https://github.com/wgailey24/simple_calendarBest regards,William Gailey wgailey24@yahoo.com On Dec 5, 2016 10:59 AM, Chris Oliver <notifications@github.com> wrote:Hah, no worries. :)
Yeah you should be able to highlight those links. You could style against .calendar-heading a which you can see here: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_week_calendar.html.erb
Or you could just add the views to your app and then add some classes in.

**Comment by wgailey** [comment]
HehPR #154On Mar 2, 2017 1:21 PM, William Gailey <wgailey24@yahoo.com> wrote:Hey Chris,I was just wondering if you reviewed the PR at https://github.com/wgailey24/simple_calendarBest regards,William Gailey wgailey24@yahoo.com On Dec 5, 2016 10:59 AM, Chris Oliver <notifications@github.com> wrote:Hah, no worries. :)
Yeah you should be able to highlight those links. You could style against .calendar-heading a which you can see here: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_week_calendar.html.erb
Or you could just add the views to your app and then add some classes in.

**Comment by wgailey** [comment]
Hey Chris,Just wondering if you ever had a chance to review PR #154 by wgailey24Best regards,William Gailey On Dec 7, 2016 10:10 AM, Chris Oliver <notifications@github.com> wrote:Feel free to shoot me a PR for it, I don't have any time to add it myself at the moment.

**Comment by excid3** [comment]
Just merged it, sorry for the delay!
