### ISSUE TITLE
I'm not seeing the day # in the month view

### ISSUE THREAD

**Issue by xdotcommer** [excid3/simple_calendar#155]
The screenshot shows the day # in the upper left hand corner of each day in the month view.  That is not rendering for me.

**Comment by excid3** [comment]
You have to render it out yourself. The date gets passed into the block so you can render the date however you like.

Use this from the examples and you'll see it: 

```erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
```

**Comment by xdotcommer** [comment]
Ok thank you

**Comment by excid3** [comment]
Not a problem, let me know if you need anything else!

**Comment by whitmanc** [comment]
just a note, here is a reference to the actual code to show the day number (instead of a date): https://github.com/excid3/simple_calendar/issues/161#issuecomment-280429431
