### ISSUE TITLE
is it a way to customize the td_classes_for(day) function?

### ISSUE THREAD

**Issue by joezhang** [excid3/simple_calendar#156]
`def td_classes_for(day)
      today = Date.current

      td_class = ['day']
      td_class << "wday-#{day.wday.to_s}"
      td_class << 'today'         if today == day
      td_class << 'past'          if today > day
      td_class << 'future'        if today < day
      td_class << 'start-date'    if day.to_date == start_date.to_date
      td_class << 'prev-month'    if start_date.month != day.month && day < start_date
      td_class << 'next-month'    if start_date.month != day.month && day > start_date
      td_class << 'current-month' if start_date.month == day.month
      td_class << 'has-events'    if sorted_events.fetch(day, []).any?

      td_class
    end`

**Comment by joezhang** [comment]
I want to add an condition as below:

`def td_classes_for(day,x)
...
td_class << 'unavailable' if sorted_events.fetch(day, []).count > x
...
`

**Comment by excid3** [comment]
It would be best to just install the simple_calendar views and call your own helper for the td class alongside this one that way you don't have to override the gem's code at all.
