### ISSUE TITLE
is there a way to make this work with google calendar

### ISSUE THREAD

**Issue by mrfollowfollow** [excid3/simple_calendar#157]
is there a way to make this work with google calendar API? as that would be ideal. thanks.

**Comment by excid3** [comment]
Yeah, I'm sure you could. You can just retrieve the events and pipe them into the calendar. You'll need to make sure to use the time attribute from there, so you might need to create your own custom object for it, but that shouldn't be too hard.

**Comment by mrfollowfollow** [comment]
perfect thank you very much 👍
