### ISSUE TITLE
current event

### ISSUE THREAD

**Issue by antiantivirus** [excid3/simple_calendar#158]
is it possible to get event data for the current event? i need this for a radio website, to have the current show that is on air.

**Comment by excid3** [comment]
This is entirely up to you to implement, but roughly I'd say you can just look at the events where the start_time attribute matches the current date. Then if your events (shows) are hourly or whatever, you can always highlight the one where the hour matches the current one. This would just be some Ruby logic you would write in a helper to add the proper CSS classes to each event you print out. All of this would happen inside a helper and inside the calendar block that loops to print out events.
