### ISSUE TITLE
Is there another gem needed to use this one?

### ISSUE THREAD

**Issue by Waleeta** [excid3/simple_calendar#159]
I installed this gem, included it in the gemfile, ran bundle install, but 'calendar' is an 'undefined method' no matter what else I do.

**Comment by excid3** [comment]
Did you restart your Rails app after running bundle?

**Comment by Waleeta** [comment]
I did - but that gave me a different error: 'calendar requires a blocK'.

**Comment by excid3** [comment]
👍 Great, so now see the examples in the readme to see how to pass in the block.

**Comment by Waleeta** [comment]
Yup, working on it, thanks!
