### ISSUE TITLE
Year by months calendar view

### ISSUE THREAD

**Issue by sylverfyst** [excid3/simple_calendar#160]
I'm currently using this gem, it's awesome by the way, but I was wondering if there was a lighter weight way to display 12+ months on the screen at once without looping through all the month's instances of the calendar.  Currently I'm rendering it like so: 

```
<div class ="calendars">
	<% @plan_range.each_with_index do |month, i| %>
		<%= month_calendar events: @month_events[i], start_date: month do |date, events| %>
		  	<%= date %>
		  	<% @envs = environment_overlap(events) %>
		  	<% if @envs.length <= 1 %>
			  	<% events.each do |event| %>
			  		<a href="#" class="event_link"><div id="event_<%=event.id%>" class="event <%=event.event_type%> <% if event.event_type == 'Environment' %> <%= avail_environments(event.id) %> <% end %>" data-toggle="tooltip" title="<%=event.name%>" data-release="<%=event.release_id%>">
			  			<%=date%>
			  		</div></a>
			  	<% end %>
			  <% else %>
			  	<% events.each do |event| %>
			  		<a href="#" class="event_link"><div id="event_<%=event.id%>" class="event <%=event.event_type%> <% if event.event_type == 'Environment' %> <%= avail_environments(event.id) %> <% end %>" data-toggle="tooltip" title="<% if event.event_type == 'Environment' %> <%= concat_overlap_names(@envs) %> Environment Availability <% else %> <%=event.name%> <% end %>" data-release="<%=event.release_id%>">
			  			<%=date%>		
			  		</div></a>
			  	<% end %>
			  <% end %>
		<% end %>
	<% end %>
</div>
```

which gives a view like this:

![screen shot 2017-01-27 at 3 11 28 pm](https://cloud.githubusercontent.com/assets/616011/22385975/f33b9ea4-e4a2-11e6-81e0-7c131b8b9cd6.png)

Any tips on generating all the calendars at once?

**Comment by excid3** [comment]
What you're doing is good. You've got to loop through each of the months no matter what whether it's the gem doing it or your app so I don't think there's a way to make a "lighter weight" version of it.

Are you looking for anything in particular?

**Comment by sylverfyst** [comment]
I'm just trying to speed up the app a bit, currently seeing somewhere around 5 seconds to glass performance.  I have the event types as filterable buttons, and functionally it works great, but it's just a tad slower than I would like.  It was kinda a shot in the dark kinda thing to see if my bottleneck was in the view.  But the gem's great thanks!

**Comment by excid3** [comment]
You probably want to benchmark it and figure out where the slowness is coming from. Could be the gem, could be some else. Then once you know what's slow, we can optimize it if it's the gem.

**Comment by sylverfyst** [comment]
Yeah I'm fairly certain it's not the gem, On initial load up before it hits the cache my log is getting `Completed 200 OK in 4824ms (Views: 4391.5ms | ActiveRecord: 160.0ms)`.  After it hits the cache it's loading in about 2.6 seconds `Completed 200 OK in 2642ms (Views: 2536.9ms | ActiveRecord: 74.0ms)` it's hitting

**Comment by excid3** [comment]
Yeah first requests are always slow, but 2.5s in Views is still super slow. I'm curious about which views that are taking so long. You should see logs for how long it takes to render each calendar in there as well.

**Comment by sylverfyst** [comment]
I'm seeing the vast majority of it in the index.html.erb file `Rendered release_calendar/index.html.erb within layouts/application (2503.0ms)`

**Comment by sylverfyst** [comment]
Which for the most part is just the code I copy pasted above, with the exception of a few buttons and a javascript shim to redirect IE pages

**Comment by excid3** [comment]
You should see individual lines for the calendar template too though I think. There should be one of those for each of the instances of the calendar you render. How long are those taking?

**Comment by sylverfyst** [comment]
I'm seeing a single line for the calendar template, but it's pretty quick: `Rendered simple_calendar/_month_calendar.html.erb (277.0ms)`

**Comment by excid3** [comment]
Hmm, that doesn't make much sense. If you're rendering X calendars, it should render that template X number of times... o_O

**Comment by sylverfyst** [comment]
I wonder if it's just moving those render calculations into the index.html.erb on the log?  I'm running this with Jruby-9.1.5.0 on torquebox

**Comment by excid3** [comment]
I don't think it would move those around, they always log in order when they're rendered under the request. 

277ms is still pretty slow. 6 of those would be 1662ms.

One thing that can affect the speed is the stuff you're doing inside the calendar because that will be included in the render for each day. I'm curious, how fast is it if you're just rendering out the date and no events in comparison?

**Comment by sylverfyst** [comment]
I can only test this locally as I'm running a load test to get an idea of what my production servers can handle, but without data in it I'm getting 
```
I, [2017-01-30T11:15:52.633000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (88.0ms)
I, [2017-01-30T11:15:52.660000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (24.0ms)
I, [2017-01-30T11:15:52.705000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (41.0ms)
I, [2017-01-30T11:15:52.772000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (65.0ms)
I, [2017-01-30T11:15:52.816000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (37.0ms)
I, [2017-01-30T11:15:52.838000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (20.0ms)
I, [2017-01-30T11:15:52.866000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (25.0ms)
I, [2017-01-30T11:15:52.902000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (33.0ms)
I, [2017-01-30T11:15:52.923000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (19.0ms)
I, [2017-01-30T11:15:52.944000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (18.0ms)
I, [2017-01-30T11:15:52.969000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (23.0ms)
I, [2017-01-30T11:15:52.990000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (18.0ms)
I, [2017-01-30T11:15:53.014000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (21.0ms)
I, [2017-01-30T11:15:53.036000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (20.0ms)
I, [2017-01-30T11:15:53.053000 #3928]  INFO -- :   Rendered simple_calendar/_month_calendar.html.erb (15.0ms)
I, [2017-01-30T11:15:53.054000 #3928]  INFO -- :   Rendered release_calendar/index.html.erb within layouts/application (529.0ms)
I, [2017-01-30T11:15:53.086000 #3928]  INFO -- :   Rendered layouts/_default_jumbotron.html.erb (1.0ms)
I, [2017-01-30T11:15:53.094000 #3928]  INFO -- :   Rendered layouts/_messages.html.erb (2.0ms)
I, [2017-01-30T11:15:53.099000 #3928]  INFO -- :   Rendered layouts/_drawer.html.erb (3.0ms)
D, [2017-01-30T11:15:53.125000 #3928] DEBUG -- :   [1m[35mUser Load (1.0ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."remember_token" = 'xxxxxxxxxxxxxxxxxxxxxxxxx'  ORDER BY "users"."id" ASC LIMIT 1
I, [2017-01-30T11:15:53.126000 #3928]  INFO -- :   Rendered layouts/_footer.html.erb (25.0ms)
I, [2017-01-30T11:15:53.127000 #3928]  INFO -- : Completed 200 OK in 757ms (Views: 624.3ms | ActiveRecord: 28.0ms)
D, [2017-01-30T11:15:53.531000 #3928] DEBUG -- : 
D, [2017-01-30T11:15:53.531000 #3928] DEBUG -- : 
I, [2017-01-30T11:15:53.532000 #3928]  INFO -- : Started GET "/ujs/initialize_index?calendar_id=1" for 0:0:0:0:0:0:0:1 at 2017-01-30 11:15:53 -0500
D, [2017-01-30T11:15:53.536000 #3928] DEBUG -- : 
D, [2017-01-30T11:15:53.537000 #3928] DEBUG -- : 
I, [2017-01-30T11:15:53.542000 #3928]  INFO -- : Started GET "/ujs/legend_toggle?calendar_id=1" for 0:0:0:0:0:0:0:1 at 2017-01-30 11:15:53 -0500
I, [2017-01-30T11:15:53.557000 #3928]  INFO -- : Processing by UjsController#initialize_index as 
I, [2017-01-30T11:15:53.557000 #3928]  INFO -- :   Parameters: {"calendar_id"=>"1"}
D, [2017-01-30T11:15:53.565000 #3928] DEBUG -- :   [1m[36m (2.0ms)[0m  [1mSELECT version()[0m
I, [2017-01-30T11:15:53.595000 #3928]  INFO -- : Processing by UjsController#legend_toggle as 
I, [2017-01-30T11:15:53.595000 #3928]  INFO -- :   Parameters: {"calendar_id"=>"1"}
I, [2017-01-30T11:15:53.617000 #3928]  INFO -- :   Rendered ujs/legend_toggle.js.erb (2.0ms)
I, [2017-01-30T11:15:53.621000 #3928]  INFO -- : Completed 200 OK in 24ms (Views: 22.0ms | ActiveRecord: 0.0ms)
I, [2017-01-30T11:15:53.629000 #3928]  INFO -- :   Rendered ujs/initialize_index.js.erb (13.0ms)
I, [2017-01-30T11:15:53.630000 #3928]  INFO -- : Completed 200 OK in 72ms (Views: 38.3ms | ActiveRecord: 0.0ms)
```

**Comment by excid3** [comment]
So there it shows an entry for each calendar. Something like 467ms total time.

I just ran a test locally to generate 12 calendars that just display the date: 

```
Started GET "/" for 127.0.0.1 at 2017-01-30 10:18:49 -0600
Processing by MeetingsController#index as HTML
  Rendering meetings/index.html.erb within layouts/application
  Meeting Load (0.6ms)  SELECT "meetings".* FROM "meetings"
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (4.5ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.5ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.1ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.1ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.2ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.0ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.5ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.4ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.5ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (4.0ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.4ms)
  Rendered /Users/chris/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/simple_calendar-2.2.2/app/views/simple_calendar/_month_calendar.html.erb (3.5ms)
  Rendered meetings/index.html.erb within layouts/application (83.2ms)
Completed 200 OK in 108ms (Views: 104.9ms | ActiveRecord: 0.6ms)
```

**Comment by sylverfyst** [comment]
I did change the month calendar template to style it a little differently, could this be the issue?

```
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day), id: day do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day.strftime("%d"), sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
```

**Comment by excid3** [comment]
How many events are you passing in to each calendar?

**Comment by excid3** [comment]
I can bet that most of the slowness is coming from the event grouping and sorting. It takes that array of events you pass it and pre-sorts them into a hash for faster rendering later, but the initial work it has to do is going to slow things down. I'm sure that method can be optimized.

I just generated 1830 events and passed the entire array into 12 calendars. Each calendar is taking about 1.8s to render. Doing about 150 events per calendar is about 110-170ms each.

**Comment by excid3** [comment]
Hah yeah, even just simply memoizing the sorted_events method here took my test case for 150 events per calendar from 4s to 400ms. That's a big improvement alone.

Looks like we should be able to speed this up a fair amount.

**Comment by sylverfyst** [comment]
It's averaging about 10 events per month without the environment event call

**Comment by sylverfyst** [comment]
Oh ok great! should this be a modification on my end?

**Comment by excid3** [comment]
One of the things performance wise I can't help with is the logic you're doing on your side (for rendering out the divs and stuff per day). You will probably want to run the benchmark library on that to make sure you're doing things efficiently there as well.

I'm gonna do some more tests and see what I can speed up today and I'll release a new version of the gem with the performance improvements so you won't have to do anything but update the gem when I'm done.

**Comment by sylverfyst** [comment]
GREAT! Thanks a ton for your help, I'll keep tweaking that logic to see if I can get that running a little faster, but you've been awesome.

**Comment by excid3** [comment]
No problem! You're the first that's doing some fairly heavy lifting (a single calendar isn't all that bad) so it's nice to shake out some of the warts.

I pushed up a commit to memoize that method which seems to help a lot. I think it was unnecessarily filtering the list of events multiple times for rendering which was gets slower the more events and days you render.

Other than that, I don't see any real obvious performance improvements off the top of my head. There might be some other smaller things but this one cut it down to 1/10th the speed from what I saw before which is pretty good.

**Comment by sylverfyst** [comment]
I pulled the gem from the commit like so: `gem 'simple_calendar', git: 'https://github.com/excid3/simple_calendar.git', ref: 'ef1edff'` and it seems like it's cutting the first load in about half to `Rendered release_calendar/index.html.erb within layouts/application (2157.0ms)`  I'll have to test in production when the gem version update goes through, but it looks like that's almost a 50% speed increase for this use case!

**Comment by excid3** [comment]
I'll be curious what your average is even locally for say 25 or 50 requests (not including the first load  since that's rails booting everything and it's always slower).

I'm probably going to release just that change because it'll be valuable on its own.

**Comment by excid3** [comment]
Just released that improvement by itself as 2.2.3.

I'm not sure I'll have any other easy performance tweaks to make but I'll probably keep poking at it after work. Feel free to analyze it as well in case you spot anything that could be done more efficiently.

**Comment by sylverfyst** [comment]
Well it looks like locally on average with caching I'm now loading the index in 500ms

**Comment by sylverfyst** [comment]
I'll take a poke around with both my logic and the source to see if I can get any more quick wins out of it, thanks so much!

**Comment by excid3** [comment]
That's a good improvement so far then!

**Comment by sylverfyst** [comment]
Yeah, I'll make sure to give you an update when I run it in my actual environment!

**Comment by MarcusPetri** [comment]
Good job! Can you provide the final code? I need to do a annual view too
