### ISSUE TITLE
How to display  just the day instead of the date on the month calendar.

### ISSUE THREAD

**Issue by papi83dm** [excid3/simple_calendar#161]
On the month calendar, how can I make it display  just the day  instead of the full  date?

![image](https://cloud.githubusercontent.com/assets/1123681/23036525/24b59544-f451-11e6-9d12-ca5317814372.png)

**Comment by excid3** [comment]
The first argument of the block is a date object you're free to do whatever you want with. You can use it to format the date however you like. The gem doesn't care what you do with your formatting, all in your control.

```ruby
<%= month_calendar do |date| %>
  <%= date.day %>
<% end %>
```

**Comment by papi83dm** [comment]
Thanks a lot, that did it, I appreciate the prompt respond.
