### ISSUE TITLE
Custom Calendar .new() method failing

### ISSUE THREAD

**Issue by caleyshemc** [excid3/simple_calendar#165]
I am trying to create a custom calendar based off the example provided, however I get the following error when calling `SimpleCalendar::MyCalendar.new(self)` in my template:

> wrong number of arguments (1 for 0)

When I remove `self`, I get

> undefined method `render' for [My Calendar]

Any idea what I'm doing wrong?

**Comment by caleyshemc** [comment]
For clarity, my custom calendar is in app/models/simple_calendar/custom_calendar.rb and is an exact copy of the example BusinessCalendar except for the name.

**Comment by excid3** [comment]
Not sure, maybe the block? For reference this is how it's done in the helpers: https://github.com/excid3/simple_calendar/blob/master/lib/simple_calendar/view_helpers.rb#L5

**Comment by caleyshemc** [comment]
Adding `< SimpleCalendar::Calendar` to the class fixed it. It may also be worth putting in the documentation that params should be passed to the new() method (e.g. attribute:, events:, etc).

**Comment by excid3** [comment]
Awesome, yeah it was mentioned in the paragraph but not included in the example. Will fix that.
