### ISSUE TITLE
Calendar initializes, but doesn't render

### ISSUE THREAD

**Issue by cyclingzealot** [excid3/simple_calendar#166]
Trying a simple inline erb template before moving to something more complex:

```
require 'erb'
require 'simple_calendar'
require 'rails'
require 'active_support/core_ext/hash'

simple_template = "<% SimpleCalendar::WeekCalendar.new number_of_weeks: 2 do |date| %>
  <%= date %>
  <% end %>"

renderer = ERB.new(simple_template)
debugger
output = renderer.result()
puts output
```

I get an empty output at the end of the code:
```
(byebug) n

[59, 68] in /home/jlam/programming/mergen/mergen.rb
   59: require 'active_support/core_ext/hash'
   60: 
   61: simple_template = "<% SimpleCalendar::WeekCalendar.new number_of_weeks: 2 do |date| %>
   62:   <%= date %>
   63:   <% end %>"
   64: 
   65: renderer = ERB.new(simple_template)
   66: debugger
   67: output = renderer.result()
=> 68: puts output
(byebug) output
""
```

The renderer ERB code is by the way:
```
(byebug) renderer
#<ERB:0x00000000f9e390 @safe_level=nil, @src="#coding:UTF-8\n_erbout = '';  SimpleCalendar::WeekCalendar.new number_of_weeks: 2 do |date| ; _erbout.concat \"\\n  \"\n; _erbout.concat(( date ).to_s); _erbout.concat \"\\n  \"\n;  end ; _erbout.force_encoding(__ENCODING__)", @encoding=#<Encoding:UTF-8>, @filename=nil, @lineno=0>
```

### Lack of equal sign on line 61

If I use an equal sign at the beginning of the string on line 61, I get:

```
  61: simple_template = "<%= SimpleCalendar::WeekCalendar.new number_of_weeks: 2 do |date| %>
   62:   <%= date %>
   63:   <% end %>"
   64: 
   65: renderer = ERB.new(simple_template)
   66: debugger
=> 67: output = renderer.result()
   68: puts output
(byebug) c
/home/jlam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval': (erb):1: syntax error, unexpected ')' (SyntaxError)
... number_of_weeks: 2 do |date| ).to_s); _erbout.concat "\n  "
...                               ^
(erb):3: syntax error, unexpected end-of-input, expecting ')'
;  end ; _erbout.force_encoding(__ENCODING__)
                                             ^
	from /home/jlam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from mergen.rb:67:in `<main>'
```

### Why SimpleCalendar::WeekCalendar.new ?

If I use `week_calendar` as suggested in the Read Me, I get unknown method:

```
[59, 68] in /home/jlam/programming/mergen/mergen.rb
   59: require 'active_support/core_ext/hash'
   60: 
   61: simple_template = "<% week_calendar number_of_weeks: 2 do |date| %>
   62:   <%= date %>
   63:   <% end %>"
   64: 
   65: renderer = ERB.new(simple_template)
   66: debugger
=> 67: output = renderer.result()
   68: puts output
(byebug) c
(erb):1:in `<main>': undefined method `week_calendar' for main:Object (NoMethodError)
	from /home/jlam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /home/jlam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from mergen.rb:67:in `<main>'
```

I guess this rails noob should pick up a good rails book or use erb templates.  Thank you for your time.

**Comment by excid3** [comment]
There's several problems with trying to do this. SimpleCalendar depends upon passing in a valid view context object from the controller for both rendering and looking up params for which month/week/etc it should render so you must pass in a valid object there first.

Also, if you use `<%` that just means run the Ruby code, don't capture the output. `<%=` is what is require to print the output of the calendar. Most likely that's why it's an empty string of output because you told it you didn't want the output.

Since that's all required, I'd recommend just creating a new Rails app and adding simple calendar to it really quick without any models. You can just run this in bash to setup an example real fast.

```bash
rails new calendar_test
cd calendar_test
rails g controller Main index
echo "gem 'simple_calendar'" >> Gemfile
bundle
echo "<%= week_calendar { |day| day } %>" > app/views/main/index.html.erb
rails s
# Open http://localhost:3000/main/index in your browser
```

**Comment by cyclingzealot** [comment]
That seems to have worked!  Thanks!  Got to get into the habit of using rails.

I was hoping to output the html file to my hard drive then email it to someone.  I'm thinking of using `lynx --dump` or a rake task.  Your feedback on what approach to use is welcomed if you're inclined to comment.   

To save an issue manager's time, I'll close the ticket.

Thanks again!

**Comment by excid3** [comment]
I'd say probably the easiest thing to do is a curl request to the url in the command line or just hit View Source in your browser to grab it.
