### ISSUE TITLE
README documentation for CSS classes that are applied in different scenarios?

### ISSUE THREAD

**Issue by whitmanc** [excid3/simple_calendar#169]
This gem nicely adds CSS classes to each day's table cell for previous, current, and future months, such as `prev-month`, and some other css classes, too, but it isn't documented and one must either inspect HTML elements or dig through the code to know those CSS classes are available.

Would it make sense if the pre-defined CSS classes that are applied were documented in the README? I wouldn't mind doing it if it makes sense

**Comment by excid3** [comment]
You mean this? https://github.com/excid3/simple_calendar#custom-css-classes

Feel free to send over some improvements if you like.

**Comment by whitmanc** [comment]
No idea how I missed that entire section! thx

**Comment by whitmanc** [comment]
@excid3 On that note, 2 thoughts/suggestions:

1. Moving the CSS documentation directly under the "Customizing Views" header in the "Customizing The Calendar" section. I think it would be more difficult to miss there. 
2. Moving the "Customizing The Calendar" section back to under the "Usage" section. The reason for this is that I feel like events are digging a little deeper than basic usage and general customizations. In my case, I started with basic usage, then went on to tinker with customizations to make sure it will work for my use case. Not sure if that is unique to me, though

LMK how you feel about 1 and/or 2, and I'll proceed accordingly with a PR

**Comment by excid3** [comment]
I like the first one because it's closely related to customizing the views. 

I'll propose a third option as well:

3. Generate a Table of Contents for the README since it's getting long enough to warrant one. 

Thoughts on that?

**Comment by whitmanc** [comment]
@excid3 A Table of Contents crossed my mind earlier as well and I believe it would be convenient/help folks not miss sections. We could do all 3 if you're up for it. Or, if you think a Table of Contents alone would suffice, that works, too. Personally, I don't think doing all 3 is going to hurt. How should I proceed?

**Comment by whitmanc** [comment]
One last thought on the Table of Contents, I think the only downside there would be would maintaining it. More specifically, remembering to update it and remembering to remind others to update it.

**Comment by excid3** [comment]
Sorry, was out for a couple of days. Want to just do all 3? I'm game and I don't think maintaining the TOC will be all that hard. Just gotta keep an eye on it for future PRs is all.

**Comment by whitmanc** [comment]
No worries! I will go ahead and submit a PR with all 3
