### ISSUE TITLE
Week View with day hours

### ISSUE THREAD

**Issue by ck2000** [excid3/simple_calendar#170]
Did you think about extending the week view with fleixble hours e.g. from 7:00 am to 20:00 pm? A method to add an event for exmaple from 8:00am - 10:00 am would be awesome.
Here is an visual example: https://bootsnipp.com/snippets/p1me7

**Comment by excid3** [comment]
Um, possibly. Mainly that's something that is going to differ for each app so maybe the solution is to add a snippet or helper that people can drop in for it.

Really there's nothing special to do that. It'd look like this:

```erb
<% 0.upto(23).each do |hour| %>
  <div>
    <%= Time.parse("#{hour}:00").strftime("%l %P") %>
  </div>
<% end %>
```

**Comment by girija** [comment]
Is there any way to display weekly calendar with hour view using simple calendar gem.

**Comment by excid3** [comment]
@girija You'd just paste the same snippet above into the block in your calendar and it'll create divs for each hour of the day.

**Comment by andregoldstein** [comment]
Hi Chris, thanks again for this great gem. I guess the issue with the above would be needing to create the functionality that determines which event goes in which time "slot".

I suppose it would entail filtering for each time div whether an event started inside it.

I've built this functionality on a custom calendar in JS, will give it a go in Rails. Thanks again 👍

**Comment by excid3** [comment]
Yeah, so for each block, you know the hour of the day, and you'd just filter out the list of events for that day that have a matching hour. And if they're bookable slots, you can choose what to do if you found events (don't allow booking) or did not (allow booking).
