### ISSUE TITLE
Custom Filtering

### ISSUE THREAD

**Issue by cristian-rivera** [excid3/simple_calendar#171]
Hey,

The documentation states that:

`If you pass in objects that don't respond to the attribute method (like starts_at), then all the meetings will be yielded each day. This lets you do custom filtering however you want.`

But when I follow this example and I pass an object that doesn't respond to that I receive this error:
`undefined method 'start_time' for #<Request:0x007f33c883b118>`

This is my code:

```
= month_calendar(events: @calendar_requests) do |date, requests|
  %h5
    %strong= date.day
  - requests.each do |r|
    = link_to r do
      %span.badge.event{ class: "label-#{request_status_class(r.status)}" }
        = r.user.name.gsub(/\s+.+\s+/, ' ').sub(/(?<=\s\S).+/, '.')
```

Any suggestions?

**Comment by excid3** [comment]
That comment might no longer be accurate. I'd have to do some digging on the source.

Obviously, you can just skip passing in the events and run your own loop instead. Nothing special to the gem for that. It should look roughly like:

```haml
= month_calendar do |date|
  %h5
    %strong= date.day
  - @calendar_requests.each do |r|
    = link_to r do
      %span.badge.event{ class: "label-#{request_status_class(r.status)}" }
        = r.user.name.gsub(/\s+.+\s+/, ' ').sub(/(?<=\s\S).+/, '.')
```

**Comment by cristian-rivera** [comment]
Awesome thanks, it's been a long week I should've thought of that!

**Comment by excid3** [comment]
That's always how it goes. :) Another set of eyeballs can go a long ways. 

Let me know if that doesn't work out for ya. I haven't used it too much with Haml myself so there is a chance for scoping issues possibly.

**Comment by cristian-rivera** [comment]
I've been using this gem for over a year with HAML and haven't had one issue!

**Comment by excid3** [comment]
That's fantastic to hear. 🤘
