### ISSUE TITLE
Showing 2 months

### ISSUE THREAD

**Issue by breiko83** [excid3/simple_calendar#172]
I was wondering how difficult it would be to show 2 months at a time. I had a look at the views but I can't see a workaround without actually editing the gem. Can you confirm?

**Comment by wgailey** [comment]
I believe you could simply place 2 calendars use css to put them where you want and have them pull off 2 separate month settings.On Jul 13, 2017 10:48 AM, Carlo Schiesaro <notifications@github.com> wrote:I was wondering how difficult it would be to show 2 months at a time. I had a look at the views but I can't see a workaround without actually editing the gem. Can you confirm?

**Comment by excid3** [comment]
The best way is to create a class that inherits from SimpleCalendar::Calendar and overrides the date ranges so your calendar spans two months instead of one. 

For example:

```ruby
# config/initializers/simple_calendar.rb
module SimpleCalendar
  class TwoMonthCalendar < SimpleCalendar::Calendar
    private

      def date_range
        (start_date.beginning_of_month.beginning_of_week..(start_date + 1.month).end_of_month.end_of_week).to_a
      end
  end
end
```

```ruby
# app/helpers/calendar.rb
module Calendar
    def two_month_calendar(options={}, &block)
      raise 'two_month_calendar requires a block' unless block_given?
      SimpleCalendar::TwoMonthCalendar.new(self, options).render(&block)
    end
end
```

Then you can use this anywhere and the same as any of the builtin calendars like so:

```erb
<%= two_month_calendar do |day| %>
  <%= day %>
<% end %>
```
