### ISSUE TITLE
Modifying the Height of a Simple Calendar

### ISSUE THREAD

**Issue by Lucones** [excid3/simple_calendar#174]
I'm using a Simple Calendar which takes my whole content-wrapper. I'm able to change de width with CSS but I'm unable to change the Height.

Is there a way to change the size (or the height) of a calendar?

**Comment by excid3** [comment]
I'm not sure what you mean. If you add CSS to the calendar `table` or `tr`, it will set it to the heights you provide.

**Comment by Lucones** [comment]
It doesn't.
I cannot modify the general height of the calendar. I've tried putting style="width:50%;height:50%;" on several places (divs/ tables/ trs) amongst other ways of resizing (on proper CSS and etc.). The width changes fine, but the height is always absolute.

**Comment by excid3** [comment]
It absolutely does. Set it to `height: 700px` and you will see that it does.

Sounds like you've just got some CSS issues with the rest of your HTML. CSS percentage heights only relative to their parents so if you're going to specify it in percentages, you must also specify that on the parents. See: https://stackoverflow.com/a/16642908/277994

**Comment by Lucones** [comment]
I had already tried using solid values (px) instead of percentages, and it either does not change at all or it cuts the calendar (showing only part of it without the possibility to scroll down). And I believe that if it was a CSS issue, the width wouldn't work either

**Comment by excid3** [comment]
It's definitely something on your end. I can set heights on the table and trs and they all adjust accordingly. https://cl.ly/lmWr
