### ISSUE TITLE
How do you change the date format?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [excid3/simple_calendar#175]
The default date is 2017-07-30. I would like to set it to 7/30 for the month before and normal 1, 2, 3, 4, 5, 6 for days of the current month.

Lastly, I am using two different user models for the simple_calendar gem. When I click the "next" link it redirects me to the home page. I may have to setup the AJAX approach that you use. The console output is below. 

Started GET "/?start_date=2017-08-07" for 127.0.0.1 at 2017-07-30 21:51:42 -0400
Processing by HomeController#index as HTML
  Parameters: {"start_date"=>"2017-08-07"}

**Comment by excid3** [comment]
1. They're just Date objects, so it's up to you to format them. Try using strftime: https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html#method-i-strftime and http://strfti.me

2. Links to the calendar use the same path the calendar is rendered on. You can install the views to customize the links as mentioned in the readme. https://github.com/excid3/simple_calendar#customizing-views

**Comment by RailsCod3rFuture** [comment]
thanks
