### ISSUE TITLE
links to previous and next month do not work

### ISSUE THREAD

**Issue by Hatemachine01** [excid3/simple_calendar#179]
Hi 

I am having trouble getting the previous /next month links to work on my calendar. Is there any configuration that I need to do or should they be set up by the gem? Currently the links are trying to redirect to the previous page that was rendered before the calendar. 

I am also new to rails so I might be forgetting to set up something. I am using Rails 5.04 and do not have any routes related to the calendar on my routes.rb.

Any help would really be appreciated. Thanks!

**Comment by excid3** [comment]
The links just point to the current page with different parameters. There isn't anything you need to do to make them work. 

You'll have to share so more information as to what's going wrong for us to figure out what's going wrong.

**Comment by Hatemachine01** [comment]
Hi Chris, thank you for the quick response and thank you for this gem!

Here is my calendar view 

`<div id="calender">
<%= month_calendar events: @reuniones do |date, eventos| %>
  <%= date.day %>
  <% eventos.each do |evento| %>
    <div>
      <% if evento.status == false %>
      <% x = " *unconfirmed*" %>
      <%= link_to evento.description + x , evento %>
      <% else %>
     <% x = " *confirmed*" %>
     <%= link_to evento.description + x , evento %> 
    </div>
     <% end %>
     <% end %>
<% end %>`
  
and theses are the urls the links are generating 

next : `http://localhost:3000/login?session%5Bemail%5D=XXX%40gmail.com&session%5Bpassword%5D=[FILTERED]&start_date=2017-09-04`

previous : `http://localhost:3000/login?session%5Bemail%5D=XXXX%40gmail.com&session%5Bpassword%5D=[FILTERED]&start_date=2017-07-30`


Please let me know any other info you might need.

**Comment by excid3** [comment]
Odd, it looks like your app is not doing a redirect after login or something so it's using the /login url I would guess. I'm not sure how you have your logins setup, but you'll probably want to look into that since the urls generated come are from /login.

**Comment by Hatemachine01** [comment]
You are correct. I just changed it to a redirect and it is working now. Thank you!

**Comment by excid3** [comment]
That was easier than expected! 🍻  Glad that fixed it!
