### ISSUE TITLE
Calendar not rendering correctly

### ISSUE THREAD

**Issue by limsammy** [excid3/simple_calendar#181]
I have gone through the barebones setup and have required the css in my application.css stylesheet and required Bootstrap for my project.

Why does my calendar end up looking like this?

<img width="1429" alt="screen shot 2017-09-05 at 9 36 23 am" src="https://user-images.githubusercontent.com/10293366/30069402-e636499c-921d-11e7-85a5-77f611973567.png">

**Comment by limsammy** [comment]
I have a single model with a single view, index, which I have put this: 

```
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
```

**Comment by excid3** [comment]
Probably because of Bootstrap changes or something. You can inspect the css and see if these are being applied:

https://github.com/excid3/simple_calendar/blob/master/app/assets/stylesheets/simple_calendar.scss

It may need some updating for Bootstrap.

**Comment by limsammy** [comment]
@excid3 Can't seem to get it to work. Gonna keep playing around with it, will let you know if I get anything working.

**Comment by excid3** [comment]
Please do! If I get some free time this week I can try and poke around but it will probably be a while. 

Are you using Bootstrap 3 or 4 btw?

**Comment by limsammy** [comment]
@excid3 I'm on 3.3.7 currently.

**Comment by excid3** [comment]
Okay cool, that's what I figured. Good to know.

Btw, you can try copying and pasting the css from the gem directly into your app for quicker testing of changes. May help you find what's missing a bit faster that way.

**Comment by jayl109** [comment]
I am having the same problem, any advice on how to fix it?

**Comment by kranthi1027** [comment]
I'm also facing the same problem. Anyone solved this yet?

**Comment by runn3r85** [comment]
I solved this by adding the simple calendar css to my application.scss file. 
```
*= require simple_calendar
```
Running bootstrap 3.3.7 and rails 5.1

**Comment by bradbajuz** [comment]
Importing the css to the application.scss resolves the problem:

`@import "simple_calendar";`

Also running Bootstrap 3.3.7 and Rails 5.1

Not really a bug but probably should add to the README

**Comment by joshterry55** [comment]
I am still having this issue. running rails 4.2. Anyone solved this?

**Comment by nicholasshirley** [comment]
@bradbajuz this worked for me in development, but if I try to precompile assets, I get an error that file is not found or unreadable. Did you run into this?

**Comment by iraszl** [comment]
Adding  @import "simple_calendar"; to app/assets/stylesheets/application.scss does work partially, but the date is not shown as a single number instead as a full date. See screenshoot: https://imgur.com/a/fPITGrj

**Comment by sera1996** [comment]
running Bootstrap 4.1.1 and Rails 5.2.4.
writing in Slim returns the following html.
the table is rendered outside its parent css class and this seems to be the reason why css isn't applied correctly.


![simple_calendar](https://user-images.githubusercontent.com/54343301/80309169-334faa00-880e-11ea-8354-df345b3a6b29.PNG)
![simple_calendar2](https://user-images.githubusercontent.com/54343301/80309173-38145e00-880e-11ea-9b40-d02e2b60f1b3.PNG)

**Comment by excid3** [comment]
@sera1996 HAML required some exception handling for proper rendering, so possibly SLIM has similar issues. Create a new issue with an example repo that reproduces the issue and I can take a look.
