### ISSUE TITLE
Incorrect illustration of events in Weekly view

### ISSUE THREAD

**Issue by Aiurek** [excid3/simple_calendar#183]
Just realized the following: If the end time of an event is set after midnight, the event duration is not properly illustrated anymore.

![sc](https://user-images.githubusercontent.com/27865200/30431776-011bd972-9960-11e7-9dc6-f296288c687f.png)

**Comment by excid3** [comment]
Simple Calendar does support multi-day events so if you use that feature to use both start_time and end_time, you will see the event displayed on both days.

It's up to you to render it with CSS if you're trying to display things in an hourly format like Google does. The gem doesn't come with anything for rendering out the hours.

**Comment by Aiurek** [comment]
I accidentally hit the wrong repository... sorry for that :-/ Thank you anyway :-)
