### ISSUE TITLE
NoMethod Error

### ISSUE THREAD

**Issue by chelseaconard** [excid3/simple_calendar#189]
Hello,

I am getting the error message below. How can I fix it? I put the html.erb code of calendar, month, and weeks into app>views>simple_calendar.

<img width="1007" alt="screen shot 2017-12-08 at 4 08 36 pm" src="https://user-images.githubusercontent.com/14115700/33785301-6088fec0-dc32-11e7-8cf8-6f3104b189a9.png">

Thank you!
Chelsea

**Comment by excid3** [comment]
Did you restart your Rails app after installing?

**Comment by chelseaconard** [comment]
That corrected the issue! Thank you so much. 

Another quick question--How do I add styling from here?

<img width="980" alt="screen shot 2017-12-08 at 4 25 01 pm" src="https://user-images.githubusercontent.com/14115700/33785753-727e8efe-dc34-11e7-9ae5-02a6a62e642c.png">

I added the code below to my application.css
<img width="223" alt="screen shot 2017-12-08 at 4 25 58 pm" src="https://user-images.githubusercontent.com/14115700/33785787-911baf86-dc34-11e7-9296-e445606e285e.png">

<img width="319" alt="screen shot 2017-12-08 at 4 26 07 pm" src="https://user-images.githubusercontent.com/14115700/33785780-8e331d36-dc34-11e7-8119-defc2c5ab4ce.png"> (etc.)

**Comment by excid3** [comment]
Yay! 😄 

This file has some example SCSS you can modify: https://github.com/excid3/simple_calendar/blob/master/app/assets/stylesheets/simple_calendar.scss

And if you want to import that, you can add `*= require simple_calendar` to your application.css

Personally, I would copy the contents and create your own `app/assets/stylesheets/simple_calendar.scss` file and paste it in there and make your modifications there. 

The rest of thet styles in the screenshot actually come from Bootstrap's table css which is optional if you want to use Bootstrap or not. You can replicate most of that by just writing your own CSS for the calendar.

**Comment by chelseaconard** [comment]
Thank you so so much!!! I really appreciate your help.

One more follow-up: How can I change the individual dates to double digits and alter the month in the title to look like your example, with arrows on either side?
<img width="966" alt="screen shot 2017-12-08 at 4 35 19 pm" src="https://user-images.githubusercontent.com/14115700/33786153-fb9906fa-dc35-11e7-99b9-6508149bed7b.png">
<img width="674" alt="screen shot 2017-12-08 at 4 36 56 pm" src="https://user-images.githubusercontent.com/14115700/33786171-0b6c78dc-dc36-11e7-9e67-1c21aa1752a8.png">

Chelsea

**Comment by excid3** [comment]
1. Day formatting is just using Ruby strftime. This is a helpful reference: http://www.strfti.me/

```erb
<%= month_calendar do |day| %>
  <%= day.strftime("%d")
<% end %>
```

2. You can setup a locale for that:

```yaml
# config/locales/en.yml 
en:
  simple_calendar:
    previous: "<<"
    next: ">>"
```

**Comment by chelseaconard** [comment]
Thank you so very much!!!

**Comment by excid3** [comment]
You're welcome! 🤓
