### ISSUE TITLE
Calendar requires a block

### ISSUE THREAD

**Issue by gracesaint** [excid3/simple_calendar#190]
<img width="1045" alt="screen shot 2017-12-09 at 3 30 49 pm" src="https://user-images.githubusercontent.com/22064942/33799267-4685e00a-dcf6-11e7-92fc-5b2693c83e73.png">
Hi there, 

Trying to include the simple_calendar gem on my website and am having this error. Can you help me fix it? 

thanks!

**Comment by jeffwolfram** [comment]
It looks like you need a do block. Something like 
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
