### ISSUE TITLE
Calendar not rendering events with custom ID of 10 digits.

### ISSUE THREAD

**Issue by Catmal** [excid3/simple_calendar#193]
I had to change the ID of Events I want on calendar to be 10 digits. So when I try to show the calendar with these events I get `3754074182 is out of range for ActiveModel::Type::Integer with limit 4 bytes.`
Is there a way to solve the issue?

**Comment by excid3** [comment]
This isn't a calendar problem, but a database level problem because you're working with very large numbers. Here's a related post on the topic: https://stackoverflow.com/questions/29538530/getting-error-indicating-number-is-out-of-range-for-activerecordtypeinteger
