### ISSUE TITLE
using simple calendar on slim rails

### ISSUE THREAD

**Issue by liaogz82** [excid3/simple_calendar#195]
I use slim-rails v3.1.2 and i can't get it to work with simple_calendar. Any advise?

**Comment by excid3** [comment]
You'll have to give some more details.

**Comment by liaogz82** [comment]
what details do you want to know?

I tried to put this code in `app/views/leaves/index.slim.html`

```
- month_calendar do |date|
  - date
```

This shows up

![screen shot 2018-05-09 at 10 27 58 am](https://user-images.githubusercontent.com/317035/39792534-b2de8542-5373-11e8-8eda-14b1e7c804b4.png)

**Comment by excid3** [comment]
Don't you want `=` instead of `-` because you want to output the calendar?

**Comment by liaogz82** [comment]
ok it shows. thanks

**Comment by excid3** [comment]
That was easier than I expected. :)
