### ISSUE TITLE
feature request: let users dictate the CSS classes

### ISSUE THREAD

**Issue by liaogz82** [excid3/simple_calendar#196]
I was thinking of improving the calendar. It would be good that the the table classes can be overwritten by your own customed classes

https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_month_calendar.html.erb#L8

You have CSS for everything else except table

**Comment by TayKangSheng** [comment]
@liaogz82  you can generate your own views and customise to your hearts content

https://github.com/excid3/simple_calendar/tree/314101a6423712fed81f4099d79225025e1e09a9#customizing-views
