### ISSUE TITLE
How do I stop the object from showing?

### ISSUE THREAD

**Issue by liaogz82** [excid3/simple_calendar#197]
I have a model `leave.rb`

```ruby
class Leave < ApplicationRecord
  # Associations
  belongs_to :user, optional: true

  scope :by_month, ->(month_num) { where('extract(month from start_date) = ?', month_num) }

  scope :by_year, ->(year) { where('extract(year from start_date) = ?', year) }

  def start_time
    start_date.to_datetime
  end
end
```

and I have an index file

```slim
= month_calendar events: @leave do |date, leave|
  = date

  = leave.each do |user_leave|
    div
      = user_leave.user.name.to_str
```

but it shows me this. what could be the problem?

<img width="1485" alt="screen shot 2018-05-10 at 3 13 27 pm" src="https://user-images.githubusercontent.com/317035/39857281-5a66f636-5465-11e8-8895-fed4e2a021a6.png">

**Comment by excid3** [comment]
This is just regular view stuff, not related to simple_calendar.

`=` prints out the return value
`-` does not

You don't want your each loop to use `=` because it will print out the array.
