### ISSUE TITLE
showing last month calendar by default

### ISSUE THREAD

**Issue by liaogz82** [excid3/simple_calendar#199]
How do I show `month_calendar` as last month by default instead of this month?

For example, this month is may, I don't want to show this month's calendar, I want to show last month's calendar

**Comment by excid3** [comment]
Just change the date you pass in.

Chris Oliver
http://excid3.com | @excid3 <http://twitter.com/excid3> |
http://github.com/excid3

**Comment by liaogz82** [comment]
works! thanks!
