### ISSUE TITLE
Event without Model?

### ISSUE THREAD

**Issue by larzknoke** [excid3/simple_calendar#201]
Is it possible to add events to a calendar without a `Model`.

I have a Array like this:

`[Mon, 30 Jul 2018, Tue, 31 Jul 2018, Wed, 01 Aug 2018, Thu, 02 Aug 2018, Fri, 03 Aug 2018, Sat, 04 Aug 2018, Sun, 05 Aug 2018, Thu, 16 Aug 2018, Fri, 17 Aug 2018, Sat, 18 Aug 2018, Sun, 19 Aug 2018, Thu, 23 Aug 2018, Fri, 24 Aug 2018, Sat, 25 Aug 2018, Sun, 26 Aug 2018] Array`

or this

`[{"available"=>false, "date"=>"2018-07-30"}, {"available"=>false, "date"=>"2018-07-31"}, {"available"=>false, "date"=>"2018-08-01"}, {"available"=>false, "date"=>"2018-08-02"}, {"available"=>false, "date"=>"2018-08-03"}, {"available"=>false, "date"=>"2018-08-04"}, {"available"=>false, "date"=>"2018-08-05"}, {"available"=>false, "date"=>"2018-08-16"}, {"available"=>false, "date"=>"2018-08-17"}, {"available"=>false, "date"=>"2018-08-18"}, {"available"=>false, "date"=>"2018-08-19"}, {"available"=>false, "date"=>"2018-08-23"}, {"available"=>false, "date"=>"2018-08-24"}, {"available"=>false, "date"=>"2018-08-25"}, {"available"=>false, "date"=>"2018-08-26"}] Array`

**Comment by excid3** [comment]
Yep! You just need to convert those into an object that responds to `start_time`, that way Simple Calendar knows how to sort them.

```ruby
class Event
  attr_accessor :date

  def initialize(date)
    @date = date
  end

  def start_time
    @date
  end
end
```

```ruby
  @events = [Mon, 30 Jul 2018, Tue, 31 Jul 2018, Wed, 01 Aug 2018, Thu, 02 Aug 2018, Fri, 03 Aug 2018, Sat, 04 Aug 2018, Sun, 05 Aug 2018, Thu, 16 Aug 2018, Fri, 17 Aug 2018, Sat, 18 Aug 2018, Sun, 19 Aug 2018, Thu, 23 Aug 2018, Fri, 24 Aug 2018, Sat, 25 Aug 2018, Sun, 26 Aug 2018] 

  @calendar_events = @events.map{ |date| Event.new(date) }
```

```
<%= month_calendar(events: @calendar_events) do |day, events| %>
  <%= day %>

  <div>
    <% events.each do |event| %>
      <%= event.date %> <%# These will be Event objects %>
    <% end %>
  </div>
<% end %>
```

**Comment by larzknoke** [comment]
nice, thank you very much! :)
