### ISSUE TITLE
Show events only on certain days of the week

### ISSUE THREAD

**Issue by edenisn** [excid3/simple_calendar#203]
Thanks for this gem!

How to show events only on certain days of the week (for example: monday and thuesday) in multi-event month calendar?

**Comment by excid3** [comment]
@edenisn you can just put an if statement in your block to check what day of the week it is.

```erb
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>

  <% if date.monday? || date.thursday? %>
    <% meetings.each do |meeting| %>
      <div>
        <%= meeting.name %>
      </div>
    <% end %>
  <% end %>
<% end %>
```
