### ISSUE TITLE
Custom user settings

### ISSUE THREAD

**Issue by fabersky** [excid3/simple_calendar#207]
I'm using [rails-settings](https://github.com/ledermann/rails-settings) to manage user settings like:

- calendar_type: `calendar`, `week_calendar`, `month_calendar`
- number_of_weeks: 1, 2, 3...
- number_of_days: 1, 2, 3...

Now, let's say that the user calendar_type is `week_calendar` and I want to set the `number_of_weeks`

* `<%= send "#{user.settings(:calendar).type}", number_of_weeks: 1, events: calendar_events do |date, events| %>`

**will work**, but

* `<%= send "#{user.settings(:calendar).type}", number_of_weeks: send "#{user.settings(:calendar).weeks}", events: calendar_events do |date, events| %>`

**won't work, nor**

* `<%= send "#{user.settings(:calendar).type}", "number_of_weeks: "#{user.settings(:calendar).weeks}", events: calendar_events do |date, events| %>`

Which would be the right formatting?

**Comment by excid3** [comment]
You don't need to use send for the options, you only use that to call the correct method. The rest aren't methods.

```
<%= send "#{user.settings(:calendar).type}", number_of_weeks: user.settings(:calendar).weeks, events: calendar_events do |date, events| %>
```

**Comment by fabersky** [comment]
Couldn't be easier...
Thanks @excid3 !
