### ISSUE TITLE
Calendar with recurring events (without ice_cube and recurring_select)

### ISSUE THREAD

**Issue by fabersky** [excid3/simple_calendar#208]
My events look like

> => #<Item id: 7, title: "something", created_at: "2018-09-06 17:40:11", updated_at: "2018-09-06 17:40:11", recurring_days: [2018-09-06 00:00:00 +0200, 2018-09-07 00:00:00 +0200, 2018-09-08 00:00:00 +0200, 2018-09-09 00:00:00 +0200], start_time: "2018-09-06 17:40:00">

When doing something like

```
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.name %>
    </div>
  <% end %>
<% end %>
```

with a "normal" event (without the `recurring_days` attribute), everything is fine.
But with that kind of event, it's not possible to show all the recurrences since the simple_calendar is looking at the `start_time` of the event. So it just shows one for 2018-09-06.

Is it possible to loop through the `recurring_days` array and show all the events in it?

I checked your tutorial with `ice_cube` and `recurring_select` but I'd like to just use [Montrose](https://github.com/rossta/montrose) to create the array of days and then handle it with my own method.

**Comment by excid3** [comment]
Just preprocess your items. Create a new array of objects in memory that respond to the methods that simple_calendar wants. You don't have to pass in your exact model.
