### ISSUE TITLE
month_calendar: strip days that are not in the month

### ISSUE THREAD

**Issue by acesuares** [excid3/simple_calendar#209]
Is it possible to strip the days that are not in this month from the month_calendar?
Currently, if the 1st of the month is on Wednesday, the Monday and Tuesday before it are listed as the last days of the previous month. 

Could these days that are not really in that month be suppressed?

Great gem by the way! Thanks!

**Comment by excid3** [comment]
You will always need those days to pad the week so that the days don't shift to the wrong spots.

Just check if the days is in the current month and if it is not, don't display anything inside it. You can also use CSS to hide the borders for .next-month and .prev-month.

**Comment by acesuares** [comment]
Thx, I am doing that in the custom view now:

````
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if day.month == start_date.month %>
                <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                  <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
                <% else %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
````
It would be easier to have some arguments to do that:
````
<%= month_calendar(suppress_non_month_dates: true, partial: 'kids/profile_calendar', events: @lessons, start_date: "2018-#{month}-01") do |date, lessons| %>

````
The thing is, if that non-month-day has events, and multiple months are displayed, the events are displayed twice, and that's very confusing!

**Comment by excid3** [comment]
I wouldn't put any of this inside the custom view. Just put it inside your block that calls month_calendar.

```
<%= month_calendar(suppress_non_month_dates: true, partial: 'kids/profile_calendar', events: @lessons, start_date: "2018-#{month}-01") do |date, lessons| %>
  <% if day.month == start_date.month %>
  <% end %>
<% end %>
```

**Comment by acesuares** [comment]
That makes sense. But: day is not available, but date is.
````
    <% if lessons.empty? || date.month != start_date.month %>
````
 However, start_date doesn't seem to be available.
````
undefined local variable or method `start_date' for #<#<Class:0x00007f5e8d9218f8>:0x00007f5e8e5ea7b0>
````

**Comment by acesuares** [comment]
Good call.

**Comment by turtleguyy** [comment]
Yep, having access to the start_date would be super handy inside the block that calls month_calendar — also for previous/next month reasons.

**Comment by acesuares** [comment]
Why did you close it?

**Comment by excid3** [comment]
It's 2 years old and nobody has worked on it.

**Comment by acesuares** [comment]
Ok, makes sense.
