### ISSUE TITLE
Customizing the header links

### ISSUE THREAD

**Issue by jono-booth** [excid3/simple_calendar#213]
Hi there,

Great calendar btw!

I am using a single page layout with anchor tags to different sections. I'd like to add the anchor to the next and previous links in the calendar header so that when the page loads it jumps straight to that anchor point.

Is it possible?

Thanks a mil!

**Comment by excid3** [comment]
Sure is. Just install the calendar templates into your app with the generator, and then you can add anchors to the next and previous links in those. You'll also need to add the matching ID to an element on the page so the anchor can scroll to it.

That should do the trick. 👍

**Comment by jono-booth** [comment]
Awesome! Thank you!
