### ISSUE TITLE
Pass collection of dates in attribute filter

### ISSUE THREAD

**Issue by TiagoHenriqueMoraes** [excid3/simple_calendar#217]
I need to render a collection of recurrent events in simple calendar, so for every single event I need pass a collection of days and then show every occurrence in the calendar. Something like this:

```
= week_calendar attribute: :recurrent_dates, events: posts do |date, posts|
  - posts.each do |post|
    = post.hour
```
Where `recurrent_dates` is an array of dates.

Any ideias?

**Comment by excid3** [comment]
You would need to just pass in the array of event objects into events. This means you probably need to pre-calculate it and generate items in memory to pass in. The `attribute` option just tells it which attribute to sort by, so it must be the name of date/time column, not an array of dates.

Here's how I handled recurring events which you can translate to how yours is setup:
https://gorails.com/episodes/recurring-events
