### ISSUE TITLE
Multiple types of events/ separate css for events.

### ISSUE THREAD

**Issue by TimJoy10** [excid3/simple_calendar#222]
I'm currently trying to implement this gem and I'm wondering if you are able to create different types of events with different respective classes. For example, creating a Meeting object with a background color of blue and creating an Interview object with a background color of orange.

Any help would be appreciated, thanks.

**Comment by excid3** [comment]
Yep. Just combine them into an array and pass the array in. Then check the type when you render them to do your different designs.

**Comment by TimJoy10** [comment]
How would you change the css dependent on the type? I understand putting it into an array and checking the type, just struggling to grasp how to change the color dependent on type.

**Comment by excid3** [comment]
Add a class to the div for the event based upon the type. 

```
<div class="event-<%= event.class.to_s.underscore %>">
```

Should produce

```
<div class="event-meeting">
<div class="event-interview">
```

You can refactor into a helper to keep it cleaner or customize it however you like. 👍

**Comment by TimJoy10** [comment]
Awesome, thank you!

**Comment by TimJoy10** [comment]
Update: I have gotten it to accept multiple types of objects and set their colors. However, it is only changing the color of the div they are in, not the entire block. 
![Screen Shot 2019-06-06 at 11 40 29 AM](https://user-images.githubusercontent.com/46972200/59046429-fc685280-884f-11e9-84fc-ebe80a4183fc.png)

**Comment by excid3** [comment]
Check the readme if you want to override the calendar template itself.
