### ISSUE TITLE
undefined method `reject' for ...

### ISSUE THREAD

**Issue by ryantranvn** [excid3/simple_calendar#225]
I render calendar successful but, it has error after I adapt meetings. 

`undefined method `reject' for #<MyController::Calendar:0x00005646320e05f0>`

Can you tell me why ?

**Comment by excid3** [comment]
Sounds like you're not passing in an array to the events argument, but you've passed in a Calendar object instead.

**Comment by ryantranvn** [comment]
Oh..than you so much ! I solved it
