### ISSUE TITLE
The calendar won't load event attributes

### ISSUE THREAD

**Issue by dwood-somniainc** [excid3/simple_calendar#230]
I'll give you a layout of what I did. In my show action, I set out to iterate over all of the values of a child relationship. The normal each do block works in the same view, but I get an empty array when I use the calendar.

show.html.erb
def show
@facility_events = @facility.facility_events.all
end

```
<%= month_calendar facility_events: @facility_events do |date, events| %>
<%= chart_date_formatter date %> //works
<% events.each do |event| %>
// Empty Array
<%= event.name %>
<% end %>
<% end
```

in rails console/view
@facility_events = @facility.facility_event_trackers.all
=> #<ActiveRecord::AssociationRelation [#<Facility...

**Comment by dwood-somniainc** [comment]
Does it work with associations?

**Comment by excid3** [comment]
Your example passes in `facility_events: `, but it should be named `events: ` if you want to have Simple Calendar sort, filter and yield those to your calendar each day.

**Comment by dwood-somniainc** [comment]
I tried changing it to events:, but it still doesn't add the attributes to the calendar itself.

facility_chart.html.erb
//AJAX works perfectly fine
<div id="events_calendar>
<%= render partial: "monthly_calendar", locals: {events: @facility_events} %>
</div>

_monthly_calendar.html.erb
<%= month_calendar events: @facility_events, previous_link....do |date, events| %>
<%= chart_date_formatter date %>
<% events.each do |event| %>
<%= event.name %>
<% end %>
<% end %>

If you print out the object array, you get [] except for the date attribute. So, the calendar is working but the values for facilty events won't load into the calendar.

**Comment by dwood-somniainc** [comment]
It works. I set the date back too far!

**Comment by excid3** [comment]
Hah! I've made that mistake too. 😜
