### ISSUE TITLE
unable to convert unpermitted parameters to hash

### ISSUE THREAD

**Issue by DanielSuarezCaceres** [excid3/simple_calendar#232]
I'm getting this error:

`unable to convert unpermitted parameters to hash`

when I'm trying to render a just a simple calendar with the code provided in the description:

```
<%= month_calendar do |date| %>
  <%= date %>
<% end %>
```

I have ruby 2.6.3, Rails 6.0, and simple calendar 2.0.3. I tried restarting the server but does nothing.

Anyone can help? Thank you in advance

**Comment by excid3** [comment]
Can you provide the full error?

**Comment by excid3** [comment]
Confirmed it works out of the box in Rails 6.0, uploaded an example app for you. https://github.com/excid3/simple_calendar-example

**Comment by DanielSuarezCaceres** [comment]
I just upgraded the gem and now it works. Anyway, thank you so much for quickly answering!!
