### ISSUE TITLE
Weekly calendar view

### ISSUE THREAD

**Issue by stevesizer** [excid3/simple_calendar#233]
Hi Chris,

I looking at using this gem for a project I am currently working on and all the events are week long events. What I wanted to do is render a calendar using weeks instead of days. Please see image attached.
Is this possible?

Thanks in advance.

<img width="1680" alt="Screenshot 2020-04-23 at 13 43 52" src="https://user-images.githubusercontent.com/2259478/80101327-25c5c600-8569-11ea-9424-15fd15d11470.png">

**Comment by excid3** [comment]
Yep. You'd want to build a custom Calendar object to do it, that way you can control the dates that are rendered and how many are in a row.

It's pretty simple: https://github.com/excid3/simple_calendar#custom-calendars

**Comment by excid3** [comment]
Something like this would generate a calendar like your screenshot.

Take the date from the URL, use it as the starting week, then add 15 entries by adding 1 week each time.

```ruby
class WeekCalendar < SimpleCalendar::Calendar
  private

    def date_range
      dates = [start_date.beginning_of_week]
      15.times do
         dates << (dates.last + 1.week)
      end
    end
end
```

**Comment by stevesizer** [comment]
Excellent i'll give it ago now and see how far I get. :)

**Comment by stevesizer** [comment]
**Error**
undefined method `slice' for 1:Integer

so when I check date_range it only the value 1

**View**
<%= SimpleCalendar::WeeklyCalendar.new(self, {}).render do |date| %>
      <%= date %>
    <% end %>

**Class**
class SimpleCalendar::WeeklyCalendar < SimpleCalendar::Calendar
  private

  	def week_number
      format = (Date.beginning_of_week == :sunday) ? "%U" : "%V"
      start_date.beginning_of_week.strftime(format).to_i
    end

    def number_of_weeks
      options.fetch(:number_of_weeks, 1)
    end

    def end_week
      week_number + number_of_weeks - 1
    end

    def date_range
      dates = [start_date.beginning_of_week]
      number_of_weeks.times do
         dates << (dates.last + 1.week)
      end
    end
end

**Partial**
<div class="simple-calendar">
  <div class="calendar-heading">
    
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <%= date_range %>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

**Comment by excid3** [comment]
Return the array in your `date_range` method. Right now you're returning the value of the `times` loop. That should do the trick.

**Comment by stevesizer** [comment]
Have you ever had any weird things going on between environments? I just i had everything sorted and for some reason on my staging site its not working.

first image is local and displays 21 weeks in the calendar. The second screenshot is on the staging site.

<img width="1365" alt="Screenshot 2020-04-29 at 15 41 46" src="https://user-images.githubusercontent.com/2259478/80609554-23afab80-8a30-11ea-9244-981761b40ace.png">
<img width="1391" alt="Screenshot 2020-04-29 at 15 41 20" src="https://user-images.githubusercontent.com/2259478/80609574-27dbc900-8a30-11ea-9f1b-60fa5047bef9.png">


_weekly_calendar.html.erb
<div class="simple-calendar">
  <%= date_range %>
  <%= calendar.options %>

  <table class="table table-striped">
   
    <tbody>
      <% date_range.each_slice(4) do |week| %>
        <tr>
          <td>
             <div class="periodization-event">
            <div class="date">DATE</div>
            <div class="cycle-heading">Cycle</div>
            <div class="pain-heading">OPEX Pain</div>
            <div class="sustain-heading">OPEX Sustain</div>
          </div>
          </td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

weekly_calendar.rb
class SimpleCalendar::WeeklyCalendar < SimpleCalendar::Calendar
  private

  	def week_number
      format = (Date.beginning_of_week == :sunday) ? "%U" : "%V"
      start_date.beginning_of_week.strftime(format).to_i
    end

    def number_of_weeks
      options.fetch(:number_of_weeks, 1)
    end

    def end_week
      week_number + number_of_weeks - 1
    end

    def date_range
      dates = [start_date.beginning_of_week]
      i = 1
      while i < number_of_weeks
         dates << (dates.last + 1.week)
         i = i + 1
      end

      return dates
    end
end
