### ISSUE TITLE
Rails 4.2.11.3 Patch Breaks `block` local variable

### ISSUE THREAD

**Issue by tlynam** [excid3/simple_calendar#235]
Hope you're doing well!

We're using version 2.3.0.  We just updated to Rails 4.2.11.13 and noticed we now have this error: `undefined local variable or method 'block'`.

On the page we're calling `<%= month_calendar do |date| %>`

It looks like this is the variable `block` is expected here:
https://github.com/excid3/simple_calendar/blob/master/lib/simple_calendar/calendar.rb#L26

In the new Rails patch, it excludes certain variables:
[Patch excluding reserved name](https://github.com/rails/rails/compare/v4.2.11.1...v4.2.11.3#diff-562906215bf781788ec5aaf37e958cb8R317)

This exclusion list includes the variable `block`
[Exclusion list](https://github.com/rails/rails/compare/v4.2.11.1...v4.2.11.3#diff-01f2db2585c06eca03cf014cfe51c50eR15)

I'd like to help fixing but first documenting it.

**Comment by excid3** [comment]
@tlynam good catch on this. I don't have any old Rails 4.2 apps, but it looks like specifically the security fix in 4.2.11.13 introduced this bug in simple_calendar then. https://groups.google.com/forum/#!topic/rubyonrails-security/hWuKcHyoKh0

Looks like your fix should do the trick now that `block` is a reserved `locals` name for `render`.

**Comment by tlynam** [comment]
Closing because the fix was merged
