### ISSUE TITLE
Group Calendars Together

### ISSUE THREAD

**Issue by T-Quill** [excid3/simple_calendar#237]
I'm currently using Simple Calendar, and I'm really loving it. I was wondering whether it'd be possible to implement a function to group calendars together. I have a lot of subscription calendars and shared calendars, and right now if I want to switch between all my (for example) various work calendars and all my various school calendars, I have to switch them all on/off individually, which is a lot of clicks. Would it be possible to make a group, assign calendars to it, and then be able to toggle them on/off by just clicking the group? I could have, for example, a Work group calendar, a School group calendar, etc. I know Business Calendar 2 gives the ability to 'favourite' calendars/calendar groups and display these on a bar to click them on/off at anytime, but just the ability to make groups and assign calendars to them (and therefore toggle them on/off with one click instead of a dozen) would be awesome- and simpler to implement, I think. Is this possible?

**Comment by excid3** [comment]
Simple Calendar renders whatever events you give it. If you want to remove items from the display, just don't pass them in to the events option when you render the calendar. That would let you choose which groups events are displayed like you're describing.

**Comment by T-Quill** [comment]
Thanks!
