### ISSUE TITLE
Display birthdays based on day+month

### ISSUE THREAD

**Issue by Vintgar** [excid3/simple_calendar#243]
Hi Chris, 

Thanks a lot for this gem. It's very usefull for me and i'm looving it.
I try to implement multi events type (meetings and birthdays). 
On my model, i've got the birthdate. So, when i want to display a contact's birthday as an event on my calendar, unless I change the birthdate with the actual year, i can't (because the year of the birthdate doest not match to this actual year)
Is there a way to display events based only on a day and a month?

Thanks for your help.
Quentin

**Comment by excid3** [comment]
Sure, just compare it with out the year, something like: `date.day == birthdate.day && date.month == birthday.month` 👍

**Comment by Vintgar** [comment]
Hey, thanks for your reply :) 

I tried what you've done, but i haven't success to implement it. I'm beginning in rails so maybe i've missed something.

in my view, i've got:

`<%= week_calendar(attribute: :start_date, end_attribute: :end_date, events: @meetings+@contacts , number_of_weeks: 1) do |date, events| %>
          <%= date.day == birthdate.day %>

          <% events.each do |event| %>
            <div>
              <%# raise %>
              <% if event.is_a? Meeting %>
                <%= event.name %>
              <% elsif event.is_a? Contact %>
                Anniversaire de <%= event.first_name %> (<%= calc_age(event.birthday) %> ans)
              <% end %>
            </div>
          <% end %>

          <% end %>`

and in my User model (which is a relationship of Contact) i've implement that method:
`  def start_date
    self.contact.birthdate ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end`

When i compare `date.day == birthdate.day` it returns me an undefined variable or method. Same when comparing `date.day == contact.birthdate.day`

**Comment by excid3** [comment]
When you specify `attribute: :start_date` that means the calendar will ask every object for `start_date`. You have to implement that on all your models.

In the case of a Contact, you want it to be birthday, so define a method that returns the birthday. 👍 

```ruby
def start_date
  birthday
end
```

**Comment by Vintgar** [comment]
Thanks again :) 
I don't want to bother you with noobie questions. But i tried and it doesn't work for me.

Maybe it's because of my way to associate 2 types of events meetings and contacts with this?: 
```<%= week_calendar(attribute: :start_date, end_attribute: :end_date, events: @meetings+@contacts , number_of_weeks: 1) do |date, events| %>```

because, when i try to compare date.day to birthdate.day, it returns me an undefined method :( 
`<%= date.day == birthdate.day && date.month == birthdate.month %>`

In my contact model i have this method
```
  def start_date
    birthdate
  end
```

In my meeting model:
```
  def start_date
    self.contact.start_date
  end
```

and my entire code in my view:
```
<%= week_calendar(attribute: :start_date, end_attribute: :end_date, events: @meetings+@contacts , number_of_weeks: 1) do |date, events| %>
          <%= date.day == birthdate.day && date.month == birthdate.month %>

          <% events.each do |event| %>
            <div>
              <%# raise %>
              <% if event.is_a? Meeting %>
                <%= event.name %>
              <% elsif event.is_a? Contact %>
                  Anniversaire de <%= event.first_name %>
              <% end %>
            </div>
          <% end %>

          <% end %>
```

**Comment by excid3** [comment]
You'll have to share the actual error otherwise I don't have information to help. 👍

**Comment by Vintgar** [comment]
sure, here a screenshot
![image](https://user-images.githubusercontent.com/12699639/93235406-ce293080-f77d-11ea-8a92-85d12b8a9bb3.png)

**Comment by excid3** [comment]
You need to access the birthdate of the object, you don't have a local variable named `birthdate`.

```erb
<%= week_calendar(attribute: :start_date, end_attribute: :end_date, events: @meetings+@contacts , number_of_weeks: 1) do |date, events| %>
  <% events.each do |event| %>
    <div>
      <% if event.is_a? Meeting %>
        <%= event.name %>
      <% elsif event.is_a? Contact %>
        <%= date.day == event.birthdate.day && date.month == event.birthdate.month %>
        Anniversaire de <%= event.first_name %>
      <% end %>
    </div>
  <% end %>
<% end %>
```

**Comment by Vintgar** [comment]
hum i tried this before. It works for contacts with birthdate in 2020 but not for contacts with "normal" birthdate

here is my result:
![image](https://user-images.githubusercontent.com/12699639/93240820-e5b7e780-f784-11ea-97bc-d3153b76df36.png)

but in fact, i have another contact which birthday is 17 of september, and this one not appears in my calendar:
![image](https://user-images.githubusercontent.com/12699639/93240906-fff1c580-f784-11ea-9f9d-f9711565b033.png)

**Comment by excid3** [comment]
Use the Rails console or byebug to test it out and check the comparison and see what's different.

**Comment by Vintgar** [comment]
it seems like my events array take only the first contact (id=4) but not the others. I don't know why?

![image](https://user-images.githubusercontent.com/12699639/93243721-e8b4d700-f788-11ea-8a5e-1e35d82a720c.png)
