### ISSUE TITLE
AJAX previous and next link still relaod the full page

### ISSUE THREAD

**Issue by AndresCarrasquilla96** [excid3/simple_calendar#246]
Hello, I'm asking this question on the repo since it has more activity than the other one.

The thing is, I have a page with several tabs, one of them is for a calendar view: 

At the index:
![index html erb](https://user-images.githubusercontent.com/34877052/95378853-c0a92700-08a1-11eb-9b06-3c5a4041e2d8.png)

Helper:
![helper](https://user-images.githubusercontent.com/34877052/95378899-d61e5100-08a1-11eb-9d45-40649b4f6887.png)

Calendar partial:
![partial](https://user-images.githubusercontent.com/34877052/95379034-0cf46700-08a2-11eb-803d-fa1fa94a33d1.png)

And the js:
![index js erb](https://user-images.githubusercontent.com/34877052/95378988-fbab5a80-08a1-11eb-9610-b3b77ea7dbeb.png)

But it keeps on reloading the whole page, please help.

**Comment by excid3** [comment]
Make sure your Rails UJS javascript is running so the links are submitted as JS requests.

**Comment by AndresCarrasquilla96** [comment]
How can I check that? I recently updated the app to Rails 5.2.0 which is supposed to include rails-ujs. The manifest looks like this: 
![imagen](https://user-images.githubusercontent.com/34877052/101500320-ee5b2c80-3933-11eb-9f81-43b2e428730c.png)


Side-note: Are there any plans of adding an on-click event to the calendar cells or is there a way to do that?

**Comment by excid3** [comment]
Looks like you're on an older app with jquery_ujs. Same thing should apply there. It's been so long that I don't remember if you need to do anything more than require jquery_ujs

I would use Stimulus JS to add events to the calendar cells. You're in an older app it looks like, so you may not have Webpacker. In that case, you can add click events with jQuery or whatever. The cells are td's in the calendar table, so you'd just select those. 

And you can install the views into your app if you want to add customize it even more. Instructions are in the readme for that.

**Comment by AndresCarrasquilla96** [comment]
What I noticed is that the `data-remote: true` attribute is not being added, apart from that I think everything else should be fine. Do you have any idea why that might be happening?
