### ISSUE TITLE
passing in events with a different attribute name (using with acts_as_bookable)

### ISSUE THREAD

**Issue by azeemh** [excid3/simple_calendar#247]
I have a service model that can be booked using acts_as_bookable. I want to show the booking events on the calendar.

acts_as_bookable has time_start and time_end attributes for each booking. I want to use the following syntax as specified in the readme but it always gives a syntax error.

using 

`<%= month_calendar(attribute: :time_start) events: @service.bookings do |date, bookings| %>`

even with nothing in the quotes after month_calendar gets an error of 

```SyntaxError (/home/azeem/alphazed/app/views/services/show.html.erb:57: syntax error, unexpected tLABEL, expecting end
...pend=  month_calendar() events: @service.bookings do |date, ...
...                        ^~~~~~~):
  
app/views/services/show.html.erb:57: syntax error, unexpected tLABEL, expecting end
```

and using

`<%= month_calendar events: @service.bookings do |date, bookings| %> `
results in 
```undefined method `start_time' for #<ActsAsBookable::Booking:0x00007f75b0ec46b8>```

I don't have access to modify the acts_as_bookable model -- i'm not the gem author so i can't write a helper method because i don't have a booking.rb file in my models to modify!!

how can i specify the attribute as time start and pass in events without getting a syntax error?

ruby 2.6.3 rails 5.2.4.1

**Comment by excid3** [comment]
You have a closing parentheses in the middle of your arguments.

It should be:

`<%= month_calendar(attribute: :time_start, events: @service.bookings) do |date, bookings| %>`

**Comment by azeemh** [comment]
Hi Chris!!!!! love your articles and videos btw.

this worked and solved it! THANKS so much for clarifying. 

Also just a reminder i know you're super busy but if you can throw this in a readme update soon that'll be awesome. otherwise at least it's here and documented for anyone else. Good day and a hat tip to you sir.

**Comment by excid3** [comment]
You're welcome and I'm glad I can help! 👍 

I'll update the readme to include parentheses around the arguments for clarity. Most of them don't have any so that can be confusing.
