### ISSUE TITLE
Week Calendar translation not working

### ISSUE THREAD

**Issue by PhilippGoecke** [excid3/simple_calendar#255]
Hi,

I18n translation of 'week' in the 'Week Calendar' is not working.

![image](https://user-images.githubusercontent.com/81357365/112462443-5574e380-8d61-11eb-8ebc-b3a1ad640043.png)

What i see is 'Week', what i would expect is 'broken_week'.

Bug Example Project:
https://github.com/PhilippGoecke/Rails-SimpleCalendar

I18n translation is (i think) correct (see https://github.com/PhilippGoecke/Rails-SimpleCalendar/blob/main/config/locales/en.yml#L37). previous and next are working properly.

I don't see the reason in this gems code (see: https://github.com/excid3/simple_calendar/blob/master/app/views/simple_calendar/_week_calendar.html.erb#L5)

So maybe this is a I18n Bug?
I just saw - this is fixed in master (see #251)

Cheers

**Comment by PhilippGoecke** [comment]
please release a new version and close this issue (already fixed in master)

**Comment by excid3** [comment]
Done

**Comment by PhilippGoecke** [comment]
Thanks!
