### ISSUE TITLE
Bootstrap styling not working.

### ISSUE THREAD

**Issue by Shuttleu** [excid3/simple_calendar#261]
I have Bootstrap included in my asset pipeline and the rest of the site works fine, however I cannot get the styling to work on this plugin. I'm using Bootstrap 5, is this version supported?

**Comment by Shuttleu** [comment]
Ok, I think I may have been mistaken. It does appear to be using bootstraps styling, but I was expecting it to look more like the image in the readme. Even after applying the default theme, it doesn't quite look the same, though very close.

I'll make the changes to the CSS to make it look as needed, and close this issue.

**Comment by excid3** [comment]
That screenshot is from Bootstrap 2 so it's very old. 😬
