### ISSUE TITLE
Need to update AJAX section in README

### ISSUE THREAD

**Issue by kenzo-tanaka** [excid3/simple_calendar#262]
Hi, I'm using this Gem at work and I love it!

I tried to implement switching calendars with Ajax, but it didn't work when I followed what was written in the [AJAX Calendars section](https://github.com/excid3/simple_calendar#ajax-calendars). Specifically, I tried the contents of this [commit](https://github.com/excid3/simple_calendar-ajax-example/commit/bd67d655866cb9da1bd061df4146f0fd44b5be96).

Instead, I added `remote: true` to the `link_to` of the view generated by the generator, and it worked fine.

> You'll need to wrap your calendar in a div, overwrite the `next_link` and `previous_link` options

I thought the content of this line was not correct.
What do you think?

**Comment by excid3** [comment]
Thanks @kenzo-tanaka 

I believe you're right. We don't have the options anymore and you just need to modify the view.

And I guess with Hotwire, the instructions would be different too. You could probably just wrap the calendar in a Turbo Frame without having to override the views.

**Comment by kenzo-tanaka** [comment]
Thanks for response @excid3 !
I created the pull request( #263 ) to update README. So if you area welcome to contribute, please check it.

> And I guess with Hotwire, the instructions would be different too. You could probably just wrap the calendar in a Turbo Frame without having to override the views.

Thanks! I'll try to implement it using Hotwire.

**Comment by excid3** [comment]
Thanks! I believe the steps should be almost the same for Hotwire

1. Generate views
2. Add an ID to the calendar. (You do not need `remote: true`)
3. Add a `turbo_stream` response in the controller that renders a Turbo Stream action to replace the calendar, like: `turbo_stream.replace("calendar", partial: "calendar")`
