### ISSUE TITLE
Feature Request: Add a "Today" button between "Previous" and "Next"

### ISSUE THREAD

**Issue by EmCousin** [excid3/simple_calendar#272]
The title explains it all. The implementation would be as simple as this in `lib/simple_calendar/simple_calendar.rb`:
```ruby
def url_for_today_view
  view_context.url_for(@params.merge(start_date_param => Date.current.iso8601))
end
```

Happy to push a Pull Request if needed

**Comment by excid3** [comment]
That would be a nice addition. 👍 PR is welcome!

**Comment by EmCousin** [comment]
@excid3 PR is here: https://github.com/excid3/simple_calendar/pull/273
