### ISSUE TITLE
Add rel="nofollow" to Previous/Next links?

### ISSUE THREAD

**Issue by ianrandmckenzie** [excid3/simple_calendar#285]
Hi there,

I am getting crawlers hammering my site with requests because the Previous/Next links a virtually endless. Is there a way to add rel="nofollow" to these links?

Thanks,

Ian

**Comment by matias-sclavi** [comment]
Hello! Have you tried generating the views and adding that attribute to the links? That could be the quickest solution to you problem.

**Comment by excid3** [comment]
Yep, that's what I would recommend.
