### ISSUE TITLE
Feature Request: allow ignoring of end_time for events

### ISSUE THREAD

**Issue by snex** [excid3/simple_calendar#300]
My application has a model with start_time and end_time attributes, but I would only like to take into account the start_time of the model when rendering it to a calendar. Currently there doesn't seem to be a way to do that.

**Comment by snex** [comment]
For anyone else with this problem, I did find a workaround. You can do the following in your view (HAML style):

```=month_calendar(events: @events.fetch_records) do |date, events|
  = date
    %div
      -events.reject { |e| e.start_time.to_date != date }.each do |e|
        ....
      -end
```

**Comment by crivotz** [comment]
I had a similar problem and I solved with `end_attribute` value, in my case I have `start_time` and `end_time` but I want use `planned_date`

Maybe you can use:
`=month_calendar(events: @events, attribute: :start_time, end_attribute: :start_time) do |date, events|`
