### ISSUE TITLE
Adding simple_calendar styles to the Rails 7 application raises an error

### ISSUE THREAD

**Issue by britaumich** [excid3/simple_calendar#309]
I included the simple_calendar gem into Rails 7 with the tailwind application.
I build the application with the command "rails new my_app --css tailwind --database=postgresql"
It added the "tailwindcss-rails" gem.

Following the instruction I added [*= require simple_calendar] into  the app/assets/stylesheets/application.css file and now I get the error 
[**LoadError (cannot load such file -- sassc)]**
when I start the application.

I read that sass is not working with Rails 7 as it worked before.

Could you please help to add simple_calendar styles to the Rails 7 application?

**Comment by excid3** [comment]
Copy and paste the CSS into your stylesheet: 
https://github.com/excid3/simple_calendar/blob/master/app/assets/stylesheets/simple_calendar.scss

**Comment by marckohlbrugge** [comment]
I ran into the same issue.

Is it worth considering switching `simple_calendar.scss` to just `simple_calendar.css`? You're not really using the SCSS functionality anyway apart from one level of nesting which is easily done manually.

Would simplify the gem a bit and prevents us non-SCSS users from having to copy/paste the stylesheet contents, making future updates a bit more of a hassle.
