### ISSUE TITLE
Events elements not rendered inside calendar

### ISSUE THREAD

**Issue by matias-sclavi** [excid3/simple_calendar#311]
Hello everyone!

I'm having an issue when using the calendar inside a ViewComponent. The events elements are rendered at the same level as the calendar's table.

### Component files

```
module Shows
  class CalendarComponent < BaseComponent
    attr_reader :shows

    def initialize(shows:)
      @shows = shows
    end
  end
end
```

```
<%= month_calendar(
      events: shows,
      attribute: :starts_at,
      end_attribute: :ends_at
    ) do |date, shows| %>
  <span class="font-medium text-sm">
    <%= date.day %>
  </span>

  <% shows.each do |show| %>
    <div class="border my-1 px-2 bg-orange-200">
      <%= render(
            Ui::LinkComponent.new(
              name: show.name,
              url: show_path(show)
            )
          ) %>
    </div>
  <% end %>
<% end %>
```

```
<%= render(Shows::CalendarComponent.new(shows: @shows)) %>
```

### Output

![image](https://user-images.githubusercontent.com/25303971/215370417-4d23867e-7057-4637-91c9-93e349dbfee3.png)

## Using calendar in view

```
<%= month_calendar(
      events: @shows,
      attribute: :starts_at,
      end_attribute: :ends_at
    ) do |date, shows| %>
  <span class="font-medium text-sm">
    <%= date.day %>
  </span>

  <% shows.each do |show| %>
    <div class="border my-1 px-2 bg-orange-200">
      <%= render(
            Ui::LinkComponent.new(
              name: show.name,
              url: show_path(show)
            )
          ) %>
    </div>
  <% end %>
<% end %>
```

### Output 
![image](https://user-images.githubusercontent.com/25303971/215370595-eec39905-4c21-4668-8125-ef995f763e24.png)

Happy to help if needed!

Thanks!

**Comment by excid3** [comment]
This is probably due to the way we render the partials. HAML had a similar issue and we fixed it by adding a capture around the yield to the block. I imagine we may need to do the same thing for erb.

**Comment by excid3** [comment]
Actually this may be the same issue that view_component has with forms and things since it changes the view_context. Not too familiar with the internals to say for sure.

**Comment by excid3** [comment]
Appears that I can fix this using `instance_exec` to change the block's binding. 🎉 

I am wondering if this will also remove the need for our special `haml_capture`...
