### ISSUE TITLE
Update README Custom Calendar render call and required view helper

### ISSUE THREAD

**Issue by pkayokay** [excid3/simple_calendar#319]
Recently upgraded to `v3.0.0` version and I had to update render calls and add view helpers when adding custom calendars. I'd love to make a PR to update the README if this is confirmed.

I have an [example app](https://github.com/pkayokay/simple-calendar-test/pull/1) with the demonstrated functionality below.

### 1. Had to update the render call
```ruby
# from
<%= SimpleCalendar::BusinessWeekCalendar.new(self, {}).render do |date| %>
  <%= date %>
<% end %>
```

<img width="874" alt="error-1" src="https://github.com/excid3/simple_calendar/assets/13375749/804828f7-1150-496b-badc-a19e4e7d3fa0">

```ruby
# to
<%= render SimpleCalendar::BusinessWeekCalendar.new(self, {}) do |date| %>
  <%= date %>
<% end %>
```

### 2. Add view helper
The block is no longer passed properly and requires a view helper to render properly. 

<img width="868" alt="error-2" src="https://github.com/excid3/simple_calendar/assets/13375749/50acde7f-c471-4f10-a32e-dcc220a45114">

```ruby
module SimpleCalendarViewHelper
  def simple_calendar_business_calendar(options = {}, &block)
    render SimpleCalendar::BusinessWeekCalendar.new(self, options, &block)
  end
end

# working view
<%= simple_calendar_business_calendar do |date| %>
  <%= date %>
<% end %>
```
<img width="503" alt="image" src="https://github.com/excid3/simple_calendar/assets/13375749/44567c85-c76a-4600-8ae0-f7cba5d633fb">

**Comment by excid3** [comment]
@pkayokay Fixed & released as v3.0.1 also updated the docs. 👍
