### ISSUE TITLE
Any interest in a HAML generator?

### ISSUE THREAD

**Issue by pmichaeljones** [excid3/simple_calendar#338]
Hi Chris,
With Haml 6, the old "hack" for the calendar isn't working anymore. HAML 6 [removed a lot of methods](https://github.com/haml/haml/blob/main/CHANGELOG.md#600), one of which is block_is_haml? and capture_haml.

```
<% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
    <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
<% else %>
    <% passed_block.call day, sorted_events.fetch(day, []) %>
<% end %>
```

This HAML code works for calendar layouts. You just need to make sure you're using HAML blocks, but if someone has HAML installed, they're most likely using it for all templates.

```
/ The capture block below only works with HAML templates
.simple-calendar
  = link_to "Previous", start_date: date_range.first - 1.day  
  = I18n.t("date.month_names")[start_date.month] 
  = start_date.year
  = link_to "Next", start_date: date_range.last + 1.day

  %table{class: 'table table-striped'}
    %thead
      %tr
        - date_range.slice(0,7).each do |day|
          %th
            = I18n.t("date.abbr_day_names")[day.wday] 

    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do 
              - capture(day, sorted_events.fetch(day, []), &passed_block)
```

If I were to add a HAML generator to the gem, is that something you would be interested in?

**Comment by excid3** [comment]
Does Haml 6 work with the regular Rails capture now? 

If so, we could just check if it responds_to the Haml methods instead. I'd rather not maintain another generator and template if we can avoid it.

**Comment by pmichaeljones** [comment]
I believe so. I've been testing out all my templates with `capture` instead of `capture_haml` and they appear to be working as expected.

```
<tbody>
  <% date_range.each_slice(7) do |week| %>
    <tr>
      <% week.each do |day| %>
        <%= content_tag :td, class: calendar.td_classes_for(day) do %>
            <% capture(day, sorted_events.fetch(day, []), &passed_block) %>
        <% end %>
     <% end %>
    </tr>
  <% end %>
</tbody>
```

**Comment by excid3** [comment]
We removed the Haml specific code back in this commit actually: https://github.com/excid3/simple_calendar/commit/9c9c8405df4232c42a372b409bc518766756a186

I think this removed the need for the `haml_capture`.

**Comment by pmichaeljones** [comment]
Ah okay. I was unaware of the `instance_exec` method. I'll give it a try tomorrow. Thanks for a great gem Chris. You're a real GEM of the rails community. *horrible pun*!
