### ISSUE TITLE
Adding custom CSS class

### ISSUE THREAD

**Issue by hafizio** [excid3/simple_calendar#60]
I am relatively new to this gem. I want to ask how to add custom CSS class. Is it integrated inside the gem? Thanks

**Comment by bcackerman** [comment]
Hey @excid3 you can in the Readme you can `You can simply run the following command to install the calendar views and then add your own helpers to the table, rows, headers, and days.` but there is no command I see to run.  Am I missing something?

**Comment by excid3** [comment]
@bcackerman I think that's a typo and should have been removed. It was from the old version or something. You can just paste those empty classes in the example into your CSS file and customize them.
