### ISSUE TITLE
Kaminari + Simple Calendar

### ISSUE THREAD

**Issue by echezbro** [excid3/simple_calendar#76]
Hi,

I'm trying to have infinite scroll on my Calendar. I'm looking to use Kaminari's "link_to_next_page" and "link_to_previous_page" but it is continuing to render the same Calendar Month every time it scrolls. I believe I need to extract the Header link code (->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}). The header left and right by using start_date param but how can I use this with Kaminari?

Can you point me in the right direction?

Thanks.

**Comment by excid3** [comment]
Whhat is your intended goal with having them work together? Presumably you
have a list of other records on the page somewhere and you want pagination
on those to change the calendar?

Chris Oliver
http://excid3.com | @excid3 <http://twitter.com/excid3> |
http://github.com/excid3

**Comment by echezbro** [comment]
Exactly. I have Reservations tied to each calendar day so a User can create a Reservation on any day of the calendar. I have that working with the regular left arrow / right arrow buttons to go to a different month but trying to display new months using infinite scroll.

**Comment by echezbro** [comment]
There must be a way to use the previous/next month calendar links as the
link_to_next_page links in Kaminari no?

If you could point me in the right direction that'd be great.

On Wed, Mar 11, 2015 at 6:41 PM, EMC <ericchesbrough@gmail.com> wrote:

> Exactly. I have Reservations tied to each calendar day so a User can
> create a Reservation on any day of the calendar. I have that working with
> the regular left arrow / right arrow buttons to go to a different month but
> trying to display new months using infinite scroll.
>
>
>
> On Mar 11, 2015, at 5:06 PM, Chris Oliver <notifications@github.com>
> wrote:
>
> Whhat is your intended goal with having them work together? Presumably you
> have a list of other records on the page somewhere and you want pagination
> on those to change the calendar?
>
> Chris Oliver
> http://excid3.com | @excid3 <http://twitter.com/excid3> |
> http://github.com/excid3
>
> On Wed, Mar 11, 2015 at 5:55 PM, echezbro <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > I'm trying to have infinite scroll on my Calendar. I'm looking to use
> > Kaminari's "link_to_next_page" and "link_to_previous_page" but it is
> > continuing to render the same Calendar Month every time it scrolls. I
> > believe I need to extract the Header link code (->(param, date_range) {
> > link_to raw("<<"), {param => date_range.first - 1.day}, remote: :true}).
> The
> > header left and right by using start_date param but how can I use this
> with
> > Kaminari?
> >
> > Can you point me in the right direction?
> >
> > Thanks.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/excid3/simple_calendar/issues/76>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/excid3/simple_calendar/issues/76#issuecomment-78382923>
> .
>
>


-- 
Eric Chesbrough
248.632.2108
ericchesbrough.com

**Comment by excid3** [comment]
Yeah, there should be a way for that. I know you can pass in extra parameters with that method. You'd probably need to add in the `start_date` param from the URL into those links.

```erb
<%= link_to_next_page @users, 'More', :params => {:start_date => params[:start_date]} %>
```

**Comment by echezbro** [comment]
Ah, man, I thought that'd do it but for some reason those params aren't coming through on the scroll. I only get the following: 
![screen shot 2015-03-12 at 9 51 07 am](https://cloud.githubusercontent.com/assets/844130/6620194/62d5d0f0-c89d-11e4-9bf7-87e4071eccd7.png)

**Comment by excid3** [comment]
Inspect the page to make sure they are on the links as you expected. Could be that maybe my syntax was wrong.

**Comment by echezbro** [comment]
Syntax appears correct. I believe the issue (or at least one) is that there is no params[:start_date]. I tested this by adding a query string to a simple link_to.

When I did = link_to "test", root_path(blah:params[:start_date) there was nothing appended to the root_path when inspected. However, when I do root_path(blah:"blah"), I see "blah" appended to the root_path url when inspecting.

**Comment by echezbro** [comment]
Yes, that's it. Using this: <%= link_to_next_page @users, 'More', :params => {:start_date => "blah"} %> passes through "blah" into my (JS) controller action. 

Now I just need to actually get the running/updated value of params[:start_date] some way outside of your method/helper.

**Comment by excid3** [comment]
Ah, yeah by default the calendar will set that param on the next and previous links. It uses that to determine the month to render. You may want to just add that into your links manually, but you'll also need to have it change on the "next" link every time you load the next set.

I think this may be a bit more complex than I originally thought.

**Comment by echezbro** [comment]
Yeah, slightly more complex than I originally thought too!

Last thing - can you expand on this a bit: "You may want to just add that into your links manually".

I'm just curious how you'd go about having it change/update the params I add to the link_to_next_page method. Perhaps you're saying use jQuery to grab the value of your next_link href and insert it as the additional params?

Thanks so much for all your help thus far, really appreciated!

**Comment by excid3** [comment]
Yeah that is probably what I would do. I'm not familiar with how Kaminari might do AJAX loading, but you would want to hook into that callback to modify the "next page" link to have `?start_date=NEXTMONTH`.

The tricky part is you're going to have the `page` attribute from Kaminari in there too so you may need to append `&start_date=NEXTMONTH` instead.

That said...I'm wondering if it is simpler to write a simple pagination from scratch so you can control it.

**Comment by echezbro** [comment]
Hm, trying to make sense of all of that ;). Unfortunately, I've never rolled my own (infinite scroll) pagination functionality. Googling resources/tutorials for this now, please link if you know of one.

Thanks so much, excid3.

**Comment by excid3** [comment]
I explained basically how it works in a screencast here, but it doesn't cover infinite scroll. https://gorails.com/episodes/pagination-with-will-paginate

Basically infinite scroll comes from JS detecting you hit the bottom of the page and then submitting an AJAX request (with jQuery). When that's successful, then the JS takes the response from the AJAX call and updates the page with the new HTML.

How are you doing the infinite scroll with Kaminari now? Did you find a snippet to use?

There may be a simpler way to do this, but I'll need to think on it.

**Comment by echezbro** [comment]
Wow. Thanks for the help.

I'm currently using the gem, 'jquery-infinite-pages'. If you know of a better/simpler one I'll switch to that.

Also, I was able to insert =link_to_next_page @reservations, "Next", :params => {:start_date => Date.today+1.month} and have the params come through as "start_date"=>"2015-04-12". Perhaps I can use something like this too, I'll have to think on the logic more though.

Thanks again, man.

**Comment by excid3** [comment]
That might work if the start date gets inserted dynamically every time. What happens when you scroll? Does it inject a new next page link with a newer date?

**Comment by echezbro** [comment]
It works the first time (scrolling goes to "April into May 2015") because start_date is set for Date.today +1.month then continues to render that same calendar for every other scroll. I'm wondering if I can use some of Ruby's DateTime helper methods to do this dynamically.

**Comment by excid3** [comment]
That may actually be the only problem here then. In that case, you want to parse the `params[:start_date]` into a date object and add 1.month to that.

So instead of Date.today...you want something like this:

```ruby
params.fetch(:start_date, Date.today).to_date + 1.month
```

That will grab the start date from the URL if it exists and add 1 month. If it doesn't exist, it defaults to Date.today and then adds 1 month. That might just do the trick!

**Comment by echezbro** [comment]
Dang. Still continuing to only increment 1 month from the Date.today on all scrolls after the first one. Since it's an AJAX (remote:true) link there's no start_date in the URL, so it keeps sending the same Date to :start_date, thus only working for the first scroll. So close.

**Comment by excid3** [comment]
Do you have a setup like this? https://gist.github.com/levymetal/5083753

**Comment by echezbro** [comment]
https://gist.github.com/echezbro/b7e648d85bd69cc8f41c

**Comment by excid3** [comment]
Hmmm, I feel like your code should work there actually. It's re-rendering the partial and replacing it on the page as I would expect.

The only thing I can think of is that maybe infinitePages doesn't send over the extra params. Do your Rails logs show the stat_date?

**Comment by echezbro** [comment]
Yes. They come through as the Date.today+1.month (4/12/15) but then don't update. Are you saying they're not coming through in the infinitePages gem? (i.e. http://stackoverflow.com/questions/12453694/infinite-scroll-plugin-modify-the-path-with-custom-query)?

Thanks so much!

**Comment by echezbro** [comment]
Wonder if using a different JS script would do it? Perhaps infinite-scroll? (https://github.com/infinite-scroll/infinite-scroll)

**Comment by excid3** [comment]
I imagine the infinitePages gem works. Let me try creating a Rails app myself using your code as an example and see if I can get it to work.

**Comment by echezbro** [comment]
You're incredible! Here is a link to the repo (zipped) if need be: http://cl.ly/082i321r3A1V

Thanks again, sir!

**Comment by excid3** [comment]
Thanks! Do you happen to have any seeds that I can use to populate the db?

**Comment by echezbro** [comment]
I'll build a seeds.rb file now.

**Comment by echezbro** [comment]
Seeds file: http://cl.ly/3r3J28343Y0A

**Comment by echezbro** [comment]
Any luck?

**Comment by excid3** [comment]
I figured it out! :) 

You need to make two changes:

1. This needs an ID and it needs to be removed because the infinitePages gem always finds the first "next page" link. That's why it keeps repeating.

```haml
=link_to_next_page(@reservations, "Next", id: "next", params: {start_date: params.fetch(:start_date, Date.today).to_date + 1.month})
```

2. Then in your show.js.erb, you want to remove the old "Next" link so that infinitePages knows to use the new one.

```erb
// Remove the old next page link
$("#next").remove()

// Append new data
$("<%=j render(:partial => 'calendar', :object => @reservations) %>").appendTo($(".infinite-table"));
```

That will make sure infinitePages always uses the new link on the page for you.

That should do it! :+1:

**Comment by echezbro** [comment]
Thanks!

Quick question - is this all you had to add? Inserted this snippet into
code base but due to the $("#next").remove(), I no longer have the "Next"
link at the bottom of my _calendar.html.haml.

I suspect an additional issue is that each time, on scroll to a new
calendar month, my JS is not being executed even though it's required in my
app.js file. Perhaps this is a turbolinks issue or maybe I need to insert a
javascript_include_tag at the bottom of my _calendar.html.haml partial so
it gets executed on every single scroll/new calendar month..?



On Sat, Mar 14, 2015 at 11:49 AM, Chris Oliver <notifications@github.com>
wrote:

> I figured it out! :)
>
> You need to make two changes:
>
>    1. This needs an ID and it needs to be removed because the
>    infinitePages gem always finds the first "next page" link. That's why it
>    keeps repeating.
>
> =link_to_next_page(@reservations, "Next", id: "next", params: {start_date: params.fetch(:start_date, Date.today).to_date + 1.month})
>
>
>    1. Then in your show.js.erb, you want to remove the old "Next" link so
>    that infinitePages knows to use the new one.
>
> // Remove the old next page link
> $("#next").remove()
>
> // Append new data
> $("<%=j render(:partial => 'calendar', :object => @reservations) %>").appendTo($(".infinite-table"));
>
> That will make sure infinitePages always uses the new link on the page for
> you.
>
> That should do it! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/excid3/simple_calendar/issues/76#issuecomment-80574473>
> .
>



-- 
Eric Chesbrough
248.632.2108
ericchesbrough.com

**Comment by excid3** [comment]
Yeah, that's all I had to change from the code you sent me. It would append a new calendar to the page with the next month every time you scrolled down. You'll want to keep that "Next" link in there so infinitePages knows what url to request each time, but you can hide it with CSS if you want it to not show up.

Here's a copy with the changes I made: http://cl.ly/aEQn

You could try disabling turbolinks to see if that helps. I have usually turned it off in my applications. You can also try jquery.turbolinks to make sure that the JS re-fires every page view.

**Comment by echezbro** [comment]
Sweet. I believe that's working, except for the data within my modal windows, but that's a different issue. 
Last thing - is there a way to have the calendar only show the current month (and not days from the prior/future month)? For example, my March calendar is rendering Feb 23-27 as well as April 1-5.

**Comment by excid3** [comment]
If you don't want them to show the dates, you can add a little if statement when you print out the date if it isn't in the current month.

Something like this would check to see if it is in the same month:

```erb
<%= date if date.month == params[:start_date].to_date.month %>
```

And then if you want to make those days look disabled, you can just add some CSS to make the background dark or something.

```css
.prev-month, .next-month {
  background: dark-gray;
}
```

More info on those default CSS classes that are available here https://github.com/excid3/simple_calendar#custom-day-classes

**Comment by echezbro** [comment]
Perfect. Thought I was done, then when I scrolled to June, the "Next" link was gone, therefore unable to continue paginating. I can't find what's causing this, I suspect something about the params[:page] or infinitepages having a maximum.

**Comment by excid3** [comment]
Hmm, I would say make sure the Next link gets render in the `_calendar.html.erb` partial so it gets added to the page as part of the JS repsonse. Also make sure the `remove()` call happens before you insert the new partial otherwise it might remove the new link as well.

**Comment by echezbro** [comment]
Hm, that's correct. Everything works great until June ;/ Have to figure out why my "Next" links are suddenly disappearing when June comes.

**Comment by echezbro** [comment]
Wow. So it turns out that the # of pages it scrolls is directly correlated to the # of Reservations I have in my DB. For instance, I was only able to scroll 4 months (March-June) because I only have 4 Reservations in my DB. I believe this is coming from Kaminari's .page method & page[params]. Glad I solved it but unfortunately will have to load Production with Dummy Data in order for it to continue scrolling..weird solution! Thanks for all your help, owe you a beer!

**Comment by excid3** [comment]
Ah yes! Your pagination won't render a clickable "next" link when you're on the last page! Of course!

That turned out to be definitely way more complicated than I originally thought. :) Glad you got everything working!

**Comment by donBigote** [comment]
Hey guys I'm curious if there is an example with an index page that doesn't use 
`Event.all`
Can will_paginate be used with simple_calendar to optimize an index page for the calendar?

**Comment by excid3** [comment]
@donBigote Yep, although that'd be kind of weird since you wouldn't know exactly which pagination links were to navigate the events and which to navigate the calendar.

I would recommend just querying for events that start or end within the month. Just write a simple `Event.where` for that.

**Comment by donBigote** [comment]
You're right. 

Is there a way to get the current month with a query like this:

`Event.where("start_time >= ? AND start_time <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month)`

**Comment by excid3** [comment]
You need to query off the date in the URL (same as simple_calendar uses) or default to Time.zone.now if there is none. That way your query will change as your calendar view changes.
