### ISSUE TITLE
One Day Per Page

### ISSUE THREAD

**Issue by echezbro** [excid3/simple_calendar#77]
Is there a way to render the Calendar (when on Mobile/Tablet) so that one table cell (TD) is show per row? I see that if each TD sits in a Calendar Row it will work but this would require changing the HTML, not CSS, based on viewport/screen-size.

Thanks!!

**Comment by excid3** [comment]
You would probably want to use the [browser](https://github.com/fnando/browser) gem to render a different calendar if it is mobile or not. You could create a custom calendar that only renders one day at a time.
