### ISSUE TITLE
simple_calendar view specs

### ISSUE THREAD

**Issue by jamescgibson** [excid3/simple_calendar#78]
When I try to write a view spec that renders a calendar, I get the following error:
```
     Failure/Error: render
     ActionView::Template::Error:
       No route matches {:action=>"show", :controller=>"clubs", :start_date=>Sun, 29 Mar 2015}
```

It all works in development and production, of course; the URL generated appends the start_date as a traditional `?=start_date` param. Any advice on stubbing this out or otherwise fixing it? I'm using Rails 4.1 and rspec 3. 

Muchas gracias for this great gem!

**Comment by excid3** [comment]
I think that's because the calendar renders links to the next and previous month. The tests probably need to know that route is available in order to generate them in the tests. I guess those methods need stubbing out in the tests?

**Comment by jamescgibson** [comment]
Yep, quite right. Figured out how to stub them and submitted a pull request, #79
