### ISSUE TITLE
Is it possible to render the 24-hours of a day in day-view?

### ISSUE THREAD

**Issue by lovishchoudhary** [excid3/simple_calendar#80]
Is it possible to render the 24-hours of a day in day-view?  So that the events of that day appear according to their start time and end time, something like google calendar?

**Comment by excid3** [comment]
Yes it is. Inside the block, you can simply iterate over the hours for each day:

```erb
<%= month_calendar do |date| %>
  <%= date %>

  <% (0).upto(23).each do |i| %>
    <div>
      <%= i %>
    </div>
  <% end %>
<% end %>
```
