### ISSUE TITLE
Weeknumbers in Calendar

### ISSUE THREAD

**Issue by schurig** [excid3/simple_calendar#81]
Is there a way to render the week number into the calendar?

**Comment by excid3** [comment]
Are you asking for the week number of the year or the week number relative to the calendar?

**Comment by schurig** [comment]
The week number of the year:

![68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f315430743173305732313264323832383256324d2f53637265656e25323053686f74253230323031332d30332d32382532306174253230392e34342e3439253230414d2e706e67-1](https://cloud.githubusercontent.com/assets/2672413/7788349/6b25453c-0237-11e5-9956-09029b3fda61.jpg)

Or at least an option to put something before the week. I would like to have the week number in front of each week-row and link it to a different page

**Comment by excid3** [comment]
You can add the following into the block. It will print out the week of the year only on Sundays. Then you can use CSS to move it into place.

```ruby
<%= date.cweek if date.sunday? %>
```

**Comment by schurig** [comment]
Thanks a lot, it worked! :)
