### ISSUE TITLE
Passing empty meeting object generates error

### ISSUE THREAD

**Issue by BeeZerk** [excid3/simple_calendar#83]
Hey,
i have a problem with the "month_calendar". If i pass a nil object it generates an error. Is there a way to fix that?

                   <%= month_calendar day_names: "date.day_names",
                                      header: {class: "calendar-header"},
                                      table: {class: "table table-bordered"},
                                      tr: {class: "calendar-row"},
                                      th: {class: "date-title"},

                                      events: @events do |date, meetings| %>

                   @events = Event.find_by_room(@room)

**Comment by BeeZerk** [comment]
@events = Event.where(:room => @room) did it for me

**Comment by excid3** [comment]
Yeah, you need an ActiveRecord::Relation or an Array to be passed in for `events` rather than a single object. :+1:
