### ISSUE TITLE
NoMethodError on 'delegate?' for nil:NilClass with RSpec

### ISSUE THREAD

**Issue by rodrigoargumedo** [excid3/simple_calendar#84]
I was just setting up simple_calendar gem with RSpec and wanted to make sure that everything is working in `irb`.

I fire the console up.
typed `require 'simple_calendar'`

then this error happened:

    NoMethodError: undefined method `delegate' for SimpleCalendar::Calendar:Class
        from /usr/local/rvm/gems/ruby-2.2.1/gems/simple_calendar-1.1.10/lib/simple_calendar/calendar.rb:3:in `<class:Calendar>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/simple_calendar-1.1.10/lib/simple_calendar/calendar.rb:2:in `<module:SimpleCalendar>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/simple_calendar-1.1.10/lib/simple_calendar/calendar.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/simple_calendar-1.1.10/lib/simple_calendar.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from (irb):4
        from /usr/local/rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

@excid3, can you confirm this bug report? it's not working at all.

**Comment by excid3** [comment]
You'll actually need to require active_support before simple_calendar because the delegate method is provided in there. http://api.rubyonrails.org/classes/Module.html#method-i-delegate

I probably don't need the dependency, but since this already relies on Rails, I figured it didn't hurt. That should get you onto the next step.

Maybe we should have an explicit require active_support in the gem?

**Comment by rodrigoargumedo** [comment]
I will explicitly load this in 'irb' and try again.



On Thu, Jun 25, 2015 at 7:04 AM -0700, "Chris Oliver" <notifications@github.com> wrote:
You'll actually need to require active_support before simple_calendar because the delegate method is provided in there. http://api.rubyonrails.org/classes/Module.html#method-i-delegate

I probably don't need the dependency, but since this already relies on Rails, I figured it didn't hurt. That should get you onto the next step.

Maybe we should have an explicit require active_support in the gem?

---

**Comment by rodrigoargumedo** [comment]
Closing this because I have a solution to this problem. Will make a pull request when I am done.

**Comment by excid3** [comment]
Yay thanks!
