### ISSUE TITLE
Add Travis CI for Continuous Integration

### ISSUE THREAD

**Issue by rodrigoargumedo** [excid3/simple_calendar#86]
Reason: We all know that we _break_ stuff without testing it out first. I use it in a couple Ruby [repositories](https://travis-ci.org/rodrigoargumedo) every single day after pushing commits and this add-on makes it easier for me to check what went wrong in tests and fix them right in the moments notice.

(**Disclaimer**: I was not paid to do this; though, It's easy and painless to setup)

Example:
[rodrigoargumedo/personal-website-rails](https://travis-ci.org/rodrigoargumedo/personal-website-rails)

```ruby
gem install travis
# You need to go in your account settings and grab a personal token key to login.
travis login --github-token #{api-key} 
travis init
```

**Comment by excid3** [comment]
Just got Travis CI setup! Image is embedded on the Readme.
