### ISSUE TITLE
What about resource view ?

### ISSUE THREAD

**Issue by ahmad19** [excid3/simple_calendar#90]
The resource view is all about seeing the calendar based on the number of people working for you and you want to see their working for today or whatever day. It is generally useful for admins.
Here is the sean kenny's work. 

Demo: http://embed.plnkr.co/cX9dH8eTjKaddJ0Gpw21/preview

**Comment by sidtri** [comment]
We can achieve this using events, except UI lacks. That gives us ability to do modify by passing classes while initializing helper. I guess !

**Comment by rodrigoargumedo** [comment]
Watch @excid3's latest [YouTube](https://www.youtube.com/watch?v=gjeFZ_HYi4c) video about it and it probably mentions about it? Correct me if I am wrong.

**Comment by rodrigoargumedo** [comment]
That might need some addressing in v2.0 as @excid3 said before. He is probably refactoring almost the entire gem.

**Comment by ahmad19** [comment]
@rodrigoargumedo that youtube link is not about the idea i mentioned here.
And probably this is an idea where we need an extra param to pass into the view as an array of resources for a day and events related to that day. So yes, the gem needs to be generalised in order to get such views.

**Comment by rodrigoargumedo** [comment]
Ah, that makes sense. Just saw the link just now and it's an interesting idea though.

**Comment by excid3** [comment]
What do you guys think about considering this as a "1 day" long calendar?

**Comment by rodrigoargumedo** [comment]
@excid3 Depends on one's need if they want to have a day long calendar. Though, the demo shows a good example of what it can look like when passed in to a view. I would think that would be fine IMO. Implementing this would be :+1: from me.
