### ISSUE TITLE
Support for Recurring Events in Calendar

### ISSUE THREAD

**Issue by sidtri** [excid3/simple_calendar#91]
http://cdn-5.askdavetaylor.com/0-blog-pics/google-calendar-repeating-event-setup-2.png

**Comment by excid3** [comment]
https://rossta.net/blog/recurring-events-in-ruby.html

New gem that came out that might be really helpful for this. We'll still need a way to store these in the database, but I think we'll be able to take advantage of it for adding those events somehow.
