### ISSUE TITLE
Is there any way to add a class to the td element based on the events attribute for a given day?

### ISSUE THREAD

**Issue by tbbooher** [excid3/simple_calendar#97]
```
= month_calendar table: {class: "calendar table table-bordered"}, events: @journal_entries do |date, entries|
          %div
            - if entries.size > 10
              # td class is 'light-gray'
```

**Comment by excid3** [comment]
I'd recommend checking out the version 2.0 of the gem that hasn't been released yet. It's almost entirely done and lets you customize that stuff easily by giving you the templates to edit.

**Comment by rodrigoargumedo** [comment]
^ I maybe biased but it's worth checking it out.

**Comment by tbbooher** [comment]
definitely -- i plan to be doing a lot with this gem

**Comment by rodrigoargumedo** [comment]
Oh yeah, please do make one!
