### ISSUE TITLE
Is there any way to add a class to the td element based on the events attribute for a given day?

### ISSUE THREAD

**Issue by tbbooher** [excid3/simple_calendar#98]
```
= month_calendar events: @journal_entries do |date, entries|
          %div
            - if entries.size > 10
              # td class is 'light-gray'
```

**Comment by tbbooher** [comment]
also wondering if v2.0 will enable this -- for example I want to fill in the entire cell with a background color if the day has an event.

**Comment by excid3** [comment]
Yes! 2.0 is actually going to give you the entire table template for the
calendar to customize.

On Thursday, July 23, 2015, Tim Booher <notifications@github.com> wrote:

> also wondering if v2.0 will enable this -- for example I want to fill in
> the entire cell with a background color if the day has an event.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/excid3/simple_calendar/issues/98#issuecomment-124266862>
> .
>


-- 
Chris Oliver
http://excid3.com | @excid3 <http://twitter.com/excid3> |
http://github.com/excid3

**Comment by tbbooher** [comment]
I'm digging in the current source to see if I can change the td class based
on the events for a given date.

**Comment by tbbooher** [comment]
easy -- i needed to remove my month_calendar_td_options in application_helper and then I get awesome classes like: ```day past current-month wday-3 has-events```
